Repository firebase/flutterfire, pull requests merged in 2019-11, with the labels that each got.

#1351 Run publish check on stable
  .cirrus.yml
  script/check_publish.sh
Labels: cla: yes

#1363 [firebase_ml_vision] Fix Android e2e test
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/firebase_ml_vision_e2e.dart
Labels: cla: yes

#1341 [all] Remove AndroidX warning
  packages/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/android/build.gradle
  packages/cloud_firestore/pubspec.yaml
  packages/cloud_functions/CHANGELOG.md
  packages/cloud_functions/android/build.gradle
  packages/cloud_functions/pubspec.yaml
  packages/firebase_admob/CHANGELOG.md
  packages/firebase_admob/android/build.gradle
  packages/firebase_admob/pubspec.yaml
  packages/firebase_analytics/CHANGELOG.md
  packages/firebase_analytics/android/build.gradle
  packages/firebase_analytics/pubspec.yaml
  packages/firebase_auth/CHANGELOG.md
  packages/firebase_auth/android/build.gradle
  packages/firebase_auth/pubspec.yaml
  packages/firebase_core/CHANGELOG.md
  packages/firebase_core/android/build.gradle
  packages/firebase_core/pubspec.yaml
  packages/firebase_database/CHANGELOG.md
  packages/firebase_database/android/build.gradle
  packages/firebase_database/pubspec.yaml
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/android/build.gradle
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/android/build.gradle
  packages/firebase_messaging/pubspec.yaml
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/android/build.gradle
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_performance/CHANGELOG.md
  packages/firebase_performance/android/build.gradle
  packages/firebase_performance/pubspec.yaml
  packages/firebase_remote_config/CHANGELOG.md
  packages/firebase_remote_config/android/build.gradle
  packages/firebase_remote_config/pubspec.yaml
  packages/firebase_storage/CHANGELOG.md
  packages/firebase_storage/android/build.gradle
  packages/firebase_storage/pubspec.yaml
Labels: cla: yes

#1378 Update READMEs with consistent contribution instructions
  packages/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/README.md
  packages/cloud_firestore/pubspec.yaml
  packages/cloud_functions/CHANGELOG.md
  packages/cloud_functions/README.md
  packages/cloud_functions/pubspec.yaml
  packages/firebase_admob/CHANGELOG.md
  packages/firebase_admob/README.md
  packages/firebase_admob/pubspec.yaml
  packages/firebase_analytics/CHANGELOG.md
  packages/firebase_analytics/README.md
  packages/firebase_analytics/pubspec.yaml
  packages/firebase_auth/CHANGELOG.md
  packages/firebase_auth/README.md
  packages/firebase_auth/pubspec.yaml
  packages/firebase_core/CHANGELOG.md
  packages/firebase_core/README.md
  packages/firebase_core/pubspec.yaml
  packages/firebase_crashlytics/CHANGELOG.md
  packages/firebase_crashlytics/README.md
  packages/firebase_crashlytics/pubspec.yaml
  packages/firebase_database/CHANGELOG.md
  packages/firebase_database/README.md
  packages/firebase_database/pubspec.yaml
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/README.md
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_in_app_messaging/CHANGELOG.md
  packages/firebase_in_app_messaging/README.md
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/README.md
  packages/firebase_messaging/pubspec.yaml
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/README.md
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_performance/CHANGELOG.md
  packages/firebase_performance/README.md
  packages/firebase_performance/pubspec.yaml
  packages/firebase_remote_config/CHANGELOG.md
  packages/firebase_remote_config/README.md
  packages/firebase_remote_config/pubspec.yaml
  packages/firebase_storage/CHANGELOG.md
  packages/firebase_storage/README.md
  packages/firebase_storage/pubspec.yaml
Labels: cla: yes

#1359 [firebase_crashlytics] Logging improvements
  packages/firebase_crashlytics/CHANGELOG.md
  packages/firebase_crashlytics/ios/Classes/FirebaseCrashlyticsPlugin.m
  packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
  packages/firebase_crashlytics/pubspec.yaml
Labels: cla: yes

#1296 [cloud_firestore] Add FieldPath
  packages/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
  packages/cloud_firestore/example/test_driver/cloud_firestore.dart
  packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
  packages/cloud_firestore/lib/cloud_firestore.dart
  packages/cloud_firestore/lib/src/field_path.dart
  packages/cloud_firestore/lib/src/firestore_message_codec.dart
  packages/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/test/cloud_firestore_test.dart
Labels: cla: yes

#1392 Remove @visibleForTesting from FirebaseApp constructor
  packages/firebase_core/lib/src/firebase_app.dart
  packages/firebase_core/test/firebase_core_test.dart
Labels: cla: yes

#1404 [CI] Use available simulator for CI
  .cirrus.yml
Labels: cla: yes

#1395 [firebase_core] bump core version to 0.4.1+4
  packages/firebase_core/CHANGELOG.md
  packages/firebase_core/pubspec.yaml
Labels: cla: yes

#1417 Remove deprecated firebase-core dependency
  packages/firebase_core/CHANGELOG.md
  packages/firebase_core/android/build.gradle
  packages/firebase_core/pubspec.yaml
Labels: cla: yes

#1334 [firebase_auth] getIdToken use actual refresh value instead of checking if object exists
  packages/firebase_auth/CHANGELOG.md
  packages/firebase_auth/example/test/firebase_auth.dart
  packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
  packages/firebase_auth/pubspec.yaml
Labels: cla: yes

#1420 [CI] update xcode to v11
  .cirrus.yml
Labels: cla: yes

#1406 Update FirebaseApp creation in tests
  packages/cloud_firestore/test/cloud_firestore_test.dart
  packages/cloud_functions/test/cloud_functions_test.dart
  packages/firebase_database/test/firebase_database_test.dart
  packages/firebase_storage/test/firebase_storage_test.dart
Labels: cla: yes

#287 [firebase_database] Support v2 android embedder.
  packages/firebase_database/CHANGELOG.md
  packages/firebase_database/android/build.gradle
  packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
  packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java
  packages/firebase_database/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/EmbeddingV1Activity.java
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/EmbeddingV1ActivityTest.java
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/MainActivity.java
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/MainActivityTest.java
  packages/firebase_database/example/android/gradle.properties
  packages/firebase_database/example/lib/main.dart
  packages/firebase_database/example/pubspec.yaml
  packages/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/example/test_driver/firebase_database_e2e_test.dart
  packages/firebase_database/example/test_driver/firebase_database_test.dart
  packages/firebase_database/pubspec.yaml
Labels: cla: yes

#282 [firebase_remote_config] Support v2 android embedder.
  packages/firebase_remote_config/CHANGELOG.md
  packages/firebase_remote_config/android/build.gradle
  packages/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
  packages/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/MethodCallHandlerImpl.java
  packages/firebase_remote_config/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_remote_config/example/android/app/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfigexample/EmbeddingV1Activity.java
  packages/firebase_remote_config/example/android/app/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfigexample/EmbeddingV1ActivityTest.java
  packages/firebase_remote_config/example/android/app/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfigexample/MainActivity.java
  packages/firebase_remote_config/example/android/app/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfigexample/MainActivityTest.java
  packages/firebase_remote_config/example/android/gradle.properties
  packages/firebase_remote_config/example/lib/main.dart
  packages/firebase_remote_config/example/pubspec.yaml
  packages/firebase_remote_config/example/test_driver/firebase_remote_config_e2e.dart
  packages/firebase_remote_config/example/test_driver/firebase_remote_config_e2e_test.dart
  packages/firebase_remote_config/example/test_driver/firebase_remote_config_test.dart
  packages/firebase_remote_config/pubspec.yaml
Labels: cla: yes

#1426 [CI] Add version to example apps
  packages/firebase_crashlytics/example/ios/Runner/Info.plist
  packages/firebase_in_app_messaging/example/ios/Runner/Info.plist
  packages/firebase_ml_vision/example/ios/Runner/Info.plist
Labels: cla: yes

#1381 [firebase_dynamic_links] Add support of expanding from short links
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
  packages/firebase_dynamic_links/ios/Classes/FirebaseDynamicLinksPlugin.m
  packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
Labels: cla: yes

#1331 Fixes strict compilation errors.
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
  packages/firebase_messaging/pubspec.yaml
Labels: cla: yes

#1370 Upgrade crashlytics to v2 plugin API
  packages/firebase_crashlytics/CHANGELOG.md
  packages/firebase_crashlytics/android/build.gradle
  packages/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
  packages/firebase_crashlytics/example/android/app/build.gradle
  packages/firebase_crashlytics/example/android/app/src/androidTest/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/EmbeddingV1ActivityTest.java
  packages/firebase_crashlytics/example/android/app/src/androidTest/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/MainActivityTest.java
  packages/firebase_crashlytics/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_crashlytics/example/android/app/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlyticsexample/EmbeddingV1Activity.java
  packages/firebase_crashlytics/example/android/app/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlyticsexample/MainActivity.java
  packages/firebase_crashlytics/example/android/gradle.properties
  packages/firebase_crashlytics/example/pubspec.yaml
  packages/firebase_crashlytics/pubspec.yaml
  packages/firebase_crashlytics/test/firebase_crashlytics_e2e.dart
Labels: cla: yes

#298 Format documentation lists (See also & Errors) correctly
  packages/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/pubspec.yaml
  packages/firebase_analytics/CHANGELOG.md
  packages/firebase_analytics/lib/firebase_analytics.dart
  packages/firebase_analytics/pubspec.yaml
  packages/firebase_auth/CHANGELOG.md
  packages/firebase_auth/lib/src/firebase_auth.dart
  packages/firebase_auth/lib/src/firebase_user.dart
  packages/firebase_auth/pubspec.yaml
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/lib/src/barcode_detector.dart
  packages/firebase_ml_vision/pubspec.yaml
Labels: cla: yes

#237 [firebase_auth] Fix NoSuchMethodError exception in `reauthenticateWithCredential`
  packages/firebase_auth/CHANGELOG.md
  packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
  packages/firebase_auth/example/test/firebase_auth.dart
  packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
  packages/firebase_auth/lib/src/firebase_user.dart
  packages/firebase_auth/lib/src/id_token_result.dart
  packages/firebase_auth/pubspec.yaml
Labels: cla: yes

#1453 [cloud_firestore] [firebase_performance] fix analyzer warnings
  packages/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/lib/src/document_change.dart
  packages/cloud_firestore/lib/src/query_snapshot.dart
  packages/cloud_firestore/pubspec.yaml
  packages/firebase_performance/CHANGELOG.md
  packages/firebase_performance/lib/src/http_metric.dart
  packages/firebase_performance/lib/src/performance_attributes.dart
  packages/firebase_performance/lib/src/trace.dart
  packages/firebase_performance/pubspec.yaml
Labels: cla: yes

#1452 [CI] Skip flaky firebase_performance driver tests
  packages/firebase_performance/CHANGELOG.md
  packages/firebase_performance/example/test_driver/firebase_performance.dart
  packages/firebase_performance/pubspec.yaml
Labels: cla: yes

#1449 [firebase_auth] Added missing Exception to the reauthenticateWithCredential docs (#1448)
  AUTHORS
  packages/firebase_auth/CHANGELOG.md
  packages/firebase_auth/lib/src/firebase_user.dart
  packages/firebase_auth/pubspec.yaml
Labels: cla: yes

#1443 [firebase_remote_config] Bumps Android Firebase dependency to 19.0.3
  packages/firebase_remote_config/CHANGELOG.md
  packages/firebase_remote_config/android/build.gradle
  packages/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/MethodCallHandlerImpl.java
  packages/firebase_remote_config/example/android/build.gradle
  packages/firebase_remote_config/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_remote_config/pubspec.yaml
Labels: cla: yes

#121 [firebase_messaging] Use UNUserNotificationCenter for ios 10+
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/README.md
  packages/firebase_messaging/android/gradle.properties
  packages/firebase_messaging/example/android/gradle.properties
  packages/firebase_messaging/example/ios/Runner/AppDelegate.m
  packages/firebase_messaging/example/test_driver/firebase_messaging.dart
  packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
  packages/firebase_messaging/lib/firebase_messaging.dart
  packages/firebase_messaging/pubspec.yaml
Labels: cla: yes, customer critical

#1473 Update CONTRIBUTING.md to allow mockito
  CONTRIBUTING.md
Labels: cla: yes

#1472 [firebase_core] Migrate to platform_interface
  packages/firebase_core/firebase_core/CHANGELOG.md
  packages/firebase_core/firebase_core/lib/firebase_core.dart
  packages/firebase_core/firebase_core/lib/src/firebase_app.dart
  packages/firebase_core/firebase_core/lib/src/firebase_options.dart
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_core/firebase_core/test/firebase_core_test.dart
Labels: cla: yes

#252 [firebase_messaging] Add an ArgumentError when passing invalid background message
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/README.md
  packages/firebase_messaging/lib/firebase_messaging.dart
  packages/firebase_messaging/pubspec.yaml
  packages/firebase_messaging/test/firebase_messaging_test.dart
Labels: cla: yes, documentation

#1372 [firebase_dynamic_links] support v2 embedding
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/android/build.gradle
  packages/firebase_dynamic_links/android/gradle.properties
  packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
  packages/firebase_dynamic_links/example/android/app/build.gradle
  packages/firebase_dynamic_links/example/android/app/src/androidTest/java/io/flutter/plugins/firebasedynamiclinks/EmbeddingV1ActivityTest.java
  packages/firebase_dynamic_links/example/android/app/src/androidTest/java/io/flutter/plugins/firebasedynamiclinks/MainActivityTest.java
  packages/firebase_dynamic_links/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_dynamic_links/example/android/app/src/main/java/io/flutter/plugins/firebasedynamiclinksexample/EmbeddingV1Activity.java
  packages/firebase_dynamic_links/example/android/app/src/main/java/io/flutter/plugins/firebasedynamiclinksexample/MainActivity.java
  packages/firebase_dynamic_links/example/android/gradle.properties
  packages/firebase_dynamic_links/example/pubspec.yaml
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_dynamic_links/test/firebase_dynamic_links_e2e.dart
Labels: cla: yes

#1476 [cloud_firestore] Fix test that used FirebaseApp.channel
  packages/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/test/cloud_firestore_test.dart
Labels: cla: yes

#1486 [firebase_core] Switch away from quiver_hashcode
  packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/platform_firebase_app.dart
  packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
Labels: cla: yes

#1369 Upgrade in-app-messaging to plugin api v2
  packages/firebase_in_app_messaging/CHANGELOG.md
  packages/firebase_in_app_messaging/android/build.gradle
  packages/firebase_in_app_messaging/android/gradle.properties
  packages/firebase_in_app_messaging/android/src/main/java/com/example/firebase_in_app_messaging/FirebaseInAppMessagingPlugin.java
  packages/firebase_in_app_messaging/example/android/app/build.gradle
  packages/firebase_in_app_messaging/example/android/app/src/androidTest/java/com/example/firebase_in_app_messaging/EmbeddingV1ActivityTest.java
  packages/firebase_in_app_messaging/example/android/app/src/androidTest/java/com/example/firebase_in_app_messaging/MainActivityTest.java
  packages/firebase_in_app_messaging/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_in_app_messaging/example/android/app/src/main/java/com/example/firebase_in_app_messaging_example/EmbeddingV1Activity.java
  packages/firebase_in_app_messaging/example/android/app/src/main/java/com/example/firebase_in_app_messaging_example/MainActivity.java
  packages/firebase_in_app_messaging/example/android/gradle.properties
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_in_app_messaging/example/test_driver/firebase_in_app_messaging.dart
  packages/firebase_in_app_messaging/example/test_driver/firebase_in_app_messaging_test.dart
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_in_app_messaging/test/firebase_in_app_messaging_e2e.dart
Labels: cla: yes

#1497 [all] Switch to pedantic analysis package
  analysis_options.yaml
  packages/cloud_firestore/analysis_options.yaml
  packages/cloud_functions/analysis_options.yaml
  packages/firebase_admob/example/lib/main.dart
  packages/firebase_admob/lib/firebase_admob.dart
  packages/firebase_analytics/analysis_options.yaml
  packages/firebase_auth/analysis_options.yaml
  packages/firebase_core/firebase_core/analysis_options.yaml
  packages/firebase_core/firebase_core_platform_interface/analysis_options.yaml
  packages/firebase_crashlytics/analysis_options.yaml
  packages/firebase_database/analysis_options.yaml
  packages/firebase_dynamic_links/analysis_options.yaml
  packages/firebase_in_app_messaging/analysis_options.yaml
  packages/firebase_messaging/analysis_options.yaml
  packages/firebase_ml_vision/analysis_options.yaml
  packages/firebase_performance/analysis_options.yaml
  packages/firebase_remote_config/analysis_options.yaml
  packages/firebase_storage/analysis_options.yaml
  pubspec.yaml
Labels: cla: yes

#1487 [firebase_core] Check `kIsWeb` in `firebase_core`
  packages/firebase_core/firebase_core/CHANGELOG.md
  packages/firebase_core/firebase_core/lib/firebase_core.dart
  packages/firebase_core/firebase_core/lib/src/firebase_app.dart
  packages/firebase_core/firebase_core/pubspec.yaml
Labels: cla: yes

#1498 Add Chrome to the Dockerfile for Cirrus
  .ci/Dockerfile
Labels: cla: yes

#1499 [firebase_messaging] Fix availability check on ios
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
  packages/firebase_messaging/pubspec.yaml
Labels: cla: yes

#1488 [firebase_core_web] Add initial implementation
  packages/firebase_core/firebase_core_web/CHANGELOG.md
  packages/firebase_core/firebase_core_web/LICENSE
  packages/firebase_core/firebase_core_web/README.md
  packages/firebase_core/firebase_core_web/ios/firebase_core_web.podspec
  packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
  packages/firebase_core/firebase_core_web/lib/src/firebase_js.dart
  packages/firebase_core/firebase_core_web/pubspec.yaml
  packages/firebase_core/firebase_core_web/test/firebase_core_web_test.dart
Labels: cla: yes
