Repository firebase/flutterfire, pull requests merged in 2020-11, with the labels that each got.

#3748 feat(cloud_firestore): add not-in & != query support
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
  packages/cloud_firestore/cloud_firestore/example/lib/main.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/web/index.html
  packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreReader.m
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/firebase_core/firebase_core/android/gradle.properties
Labels: cla: yes, ready-to-merge

#4025 fix(messaging,ios): crash when senderId null (fixes #4024)
  packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Labels: cla: yes

#4027 docs: clarify Xcode project name
  docs/installation/ios.mdx
  docs/installation/macos.mdx
Labels: cla: yes

#4039 docs: add warnings about APNs not working on simulators
  docs/messaging/notifications.mdx
  docs/messaging/usage.mdx
Labels: cla: yes

#4040 chore: upgrade website dependencies & fix image sourcing
  docs/auth/phone.mdx
  docs/auth/usage.mdx
  docs/crashlytics/reports.mdx
  docs/installation/ios.mdx
  docs/installation/macos.mdx
  docs/messaging/apple-integration.mdx
  docs/messaging/notifications.mdx
  docs/messaging/permissions.mdx
  website/docusaurus-plugins/source-api-reference.js
  website/docusaurus.config.js
  website/package.json
  website/src/theme/MDXComponents/index.tsx
  website/yarn.lock
Labels: cla: yes

#4043 fix(ios): don't replace `UNUserNotificationCenter` delegate when protocol conforms to `FlutterApplicationLifeCycleDelegate`
  packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Labels: cla: yes

#4048 refactor(messaging): use invokeMapMethod instead of invokeMethod
  packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
  packages/firebase_messaging/firebase_messaging/example/lib/main.dart
  packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/test/method_channel_tests/method_channel_messaging_test.dart
Labels: cla: yes

#3973 feat(cloud_firestore,firebase_auth): migrate firebase interop files to local repository
  .github/workflows/scripts/drive-example.sh
  melos.yaml
  packages/cloud_firestore/cloud_firestore/example/lib/main.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/instance_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/cloud_firestore_platform_interface.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/persistence_settings.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/collection_reference_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_factory_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firebase_interop.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/codec_utility.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/test/field_value_factory_web_test.dart
  packages/cloud_firestore/cloud_firestore_web/test/test_common.dart
  packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart
  packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
  packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_confirmation_result.dart
  packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart
  packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
  packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user_credential.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/firebase_interop.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/utils/utils.dart
  packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
  packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
  packages/firebase_core/firebase_core_web/lib/firebase_core_web_interop.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/app.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/app_interop.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/core.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/core_interop.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/es6_interop.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/func.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/js.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/js_interop.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
  packages/firebase_core/firebase_core_web/pubspec.yaml
Labels: cla: no

#4071 fix(messaging): potential crash (fixes #4032)
  packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
Labels: cla: yes

#4076 fix(firebase_core,web): ensure list items are converted
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Labels: cla: yes

#4092 fix(messaging,android): java String arrays should be converted to a List (fixes #4072)
  packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
Labels: cla: yes

#4091 docs(messaging): update incorrect function name
  docs/messaging/usage.mdx
Labels: cla: yes

#4079 docs(firebase_functions): updated usage doc
  docs/functions/usage.mdx
Labels: cla: yes

#3758 docs(auth): updated Email verification documentation
  docs/auth/usage.mdx
Labels: cla: yes

#3824 docs(firebase_storage): storage usage example update
  docs/storage/usage.mdx
Labels: cla: yes

#3823 docs: update readme with bug reports link
  README.md
Labels: cla: yes

#4081 docs: updated flutter_facebook_auth to ^1.0.0
  docs/versions.js
Labels: cla: yes

#3425 fix(auth,example): updated email link signin to use latest format for ActionCodeSettings
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
Labels: cla: yes

#4095 feat(firebase_core): add FirebaseException.stackTrace support
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart
  packages/firebase_core/firebase_core_platform_interface/test/firebase_exception_test.dart
Labels: cla: yes

#3675 docs(auth): add docs for Sign In with Apple
  docs/auth/social.mdx
Labels: Needs Attention, cla: yes

#4154 ci: use new GH actions path adding mechanism
  .github/workflows/scripts/install-flutter.sh
  .github/workflows/scripts/install-tools.sh
Labels: cla: yes

#4028 feat(firebase_storage): Tweaks to firebase_storage for the upcoming web version.
  packages/firebase_storage/firebase_storage/example/cors.json
  packages/firebase_storage/firebase_storage/example/lib/main.dart
  packages/firebase_storage/firebase_storage/example/lib/save_as/save_as.dart
  packages/firebase_storage/firebase_storage/example/lib/save_as/save_as_html.dart
  packages/firebase_storage/firebase_storage/example/lib/save_as/save_as_interface.dart
  packages/firebase_storage/firebase_storage/example/pubspec.yaml
  packages/firebase_storage/firebase_storage/example/test_driver/list_result_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/reference_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/test_utils.dart
  packages/firebase_storage/firebase_storage/example/web/index.html
Labels: cla: yes

#4150 fix(firebase_messaging): various data types issues in remote message
  packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
Labels: cla: yes

#4142 docs(firestore): fix typo
  docs/firestore/usage.mdx
Labels: cla: yes

#4158 chore(examples): bump gradle wrapper to 5.6.4
  packages/cloud_firestore/cloud_firestore/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/cloud_firestore/cloud_firestore/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/cloud_functions/cloud_functions/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/cloud_functions/cloud_functions/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_admob/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_admob/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_analytics/firebase_analytics/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_analytics/firebase_analytics/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_auth/firebase_auth/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_auth/firebase_auth/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_core/firebase_core/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_crashlytics/firebase_crashlytics/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_database/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_database/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_dynamic_links/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_dynamic_links/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_in_app_messaging/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_messaging/firebase_messaging/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_ml_custom/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_ml_custom/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_ml_vision/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_ml_vision/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_performance/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_performance/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_remote_config/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_storage/firebase_storage/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_storage/firebase_storage/example/android/gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#4176 docs(contributor guide): Comment out TODOs
  CONTRIBUTING.md
Labels: cla: yes

#4175 docs(firebase_storage): Fix mismatched progress calculator
  docs/storage/usage.mdx
Labels: cla: yes

#4204 test(firebase_storage): Opt-out from null safety.
  .github/workflows/scripts/drive-example.sh
  packages/firebase_storage/firebase_storage/example/pubspec.yaml
  packages/firebase_storage/firebase_storage/example/test_driver/firebase_storage_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/firebase_storage_e2e_test.dart
  packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/list_result_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/reference_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/test_utils.dart
Labels: cla: yes

#4210 chore: various CI improvements
  .github/workflows/all_plugins.yaml
  .github/workflows/scripts/start-firestore-emulator.sh
  melos.yaml
  packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e_test.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/collection_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_change_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/field_value_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/geo_point_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/instance_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/snapshot_metadata_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/timestamp_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/transaction_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/write_batch_e2e.dart
  packages/cloud_functions/cloud_functions/example/test_driver/cloud_functions_e2e.dart
  packages/cloud_functions/cloud_functions/example/test_driver/cloud_functions_e2e_test.dart
  packages/cloud_functions/cloud_functions/example/test_driver/sample.dart
  packages/firebase_analytics/firebase_analytics/example/test_driver/firebase_analytics_e2e.dart
  packages/firebase_analytics/firebase_analytics/example/test_driver/firebase_analytics_e2e_test.dart
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e.dart
  packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e_test.dart
  packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart
  packages/firebase_auth/firebase_auth/example/test_driver/test_utils.dart
  packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart
  packages/firebase_core/firebase_core/example/test_driver/firebase_core_e2e.dart
  packages/firebase_core/firebase_core/example/test_driver/firebase_core_e2e_test.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/func.dart
  packages/firebase_messaging/firebase_messaging/example/test_driver/firebase_messaging_e2e.dart
  packages/firebase_messaging/firebase_messaging/example/test_driver/firebase_messaging_e2e_test.dart
  packages/firebase_messaging/firebase_messaging/example/test_driver/instance_e2e.dart
  packages/firebase_messaging/firebase_messaging/example/test_driver/test_utils.dart
  packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/.gitignore
  packages/firebase_storage/firebase_storage_web/example/.metadata
  packages/firebase_storage/firebase_storage_web/example/README.md
  packages/firebase_storage/firebase_storage_web/example/lib/main.dart
  packages/firebase_storage/firebase_storage_web/example/pubspec.yaml
  packages/firebase_storage/firebase_storage_web/example/test_driver/all_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/all_e2e_test.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/firebase_storage_web_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/list_result_web_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/mocks/mocks.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/reference_web_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/task_snapshot_web_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/test_driver/task_web_e2e.dart
  packages/firebase_storage/firebase_storage_web/example/web/favicon.png
  packages/firebase_storage/firebase_storage_web/example/web/icons/Icon-192.png
  packages/firebase_storage/firebase_storage_web/example/web/icons/Icon-512.png
  packages/firebase_storage/firebase_storage_web/example/web/index.html
  packages/firebase_storage/firebase_storage_web/example/web/manifest.json
Labels: cla: yes

#4212 fix(firebase_core, cloud_firestore): dartify and use actual types
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
Labels: Needs Attention, cla: yes

#4157 feat(firebase_storage_web): migrate firebase interop into library
  packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/firebase_interop.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart
  packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/task_snapshot_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/task_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/utils/errors.dart
  packages/firebase_storage/firebase_storage_web/lib/src/utils/list.dart
  packages/firebase_storage/firebase_storage_web/lib/src/utils/metadata.dart
  packages/firebase_storage/firebase_storage_web/lib/src/utils/task.dart
  packages/firebase_storage/firebase_storage_web/pubspec.yaml
Labels: cla: yes

#4099 fix(firebase_auth): stop authStateChange firing twice for initial event
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#4191 feat(cloud_functions): migrate interop files
  .github/workflows/scripts/functions/package-lock.json
  .github/workflows/scripts/functions/package.json
  packages/cloud_functions/cloud_functions/example/lib/main_deprecated.dart
  packages/cloud_functions/cloud_functions/example/pubspec.yaml
  packages/cloud_functions/cloud_functions_web/lib/cloud_functions_web.dart
  packages/cloud_functions/cloud_functions_web/lib/https_callable_web.dart
  packages/cloud_functions/cloud_functions_web/lib/interop/firebase_interop.dart
  packages/cloud_functions/cloud_functions_web/lib/interop/functions.dart
  packages/cloud_functions/cloud_functions_web/lib/interop/functions_interop.dart
  packages/cloud_functions/cloud_functions_web/lib/utils.dart
  packages/cloud_functions/cloud_functions_web/pubspec.yaml
  packages/cloud_functions/cloud_functions_web/test/cloud_functions_web_test.dart
Labels: cla: yes

#4214 docs: update code doc typo
  packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_firebase_functions.dart
Labels: cla: yes

#4222 chore: Migrate iOS example projects
  packages/cloud_firestore/cloud_firestore/example/ios/Podfile
  packages/cloud_firestore/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_ml_custom/example/ios/Podfile
  packages/firebase_ml_custom/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_ml_custom/ios/firebase_ml_custom.podspec
  packages/firebase_ml_vision/example/ios/Podfile
  packages/firebase_ml_vision/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_storage/firebase_storage/example/ios/Podfile
  packages/firebase_storage/firebase_storage/example/ios/Runner.xcodeproj/project.pbxproj
Labels: cla: yes

#4219 docs: Fixed two typos in method documentation
  packages/firebase_auth/firebase_auth/lib/src/user.dart
Labels: cla: yes

#4266 fix: issue when specifying a functions region #4226
  packages/cloud_functions/cloud_functions_web/lib/interop/functions.dart
Labels: cla: yes

#4269 feat: bump android `com.android.tools.build` & `'com.google.gms:google-services` versions
  packages/cloud_firestore/cloud_firestore/android/build.gradle
  packages/cloud_firestore/cloud_firestore/example/android/build.gradle
  packages/cloud_functions/cloud_functions/android/build.gradle
  packages/cloud_functions/cloud_functions/example/android/build.gradle
  packages/firebase_admob/android/build.gradle
  packages/firebase_admob/example/android/build.gradle
  packages/firebase_analytics/firebase_analytics/android/build.gradle
  packages/firebase_analytics/firebase_analytics/example/android/build.gradle
  packages/firebase_auth/firebase_auth/android/build.gradle
  packages/firebase_auth/firebase_auth/example/android/build.gradle
  packages/firebase_core/firebase_core/android/build.gradle
  packages/firebase_core/firebase_core/example/android/build.gradle
  packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle
  packages/firebase_crashlytics/firebase_crashlytics/example/android/build.gradle
  packages/firebase_database/android/build.gradle
  packages/firebase_database/example/android/build.gradle
  packages/firebase_dynamic_links/android/build.gradle
  packages/firebase_dynamic_links/example/android/build.gradle
  packages/firebase_in_app_messaging/README.md
  packages/firebase_in_app_messaging/android/build.gradle
  packages/firebase_in_app_messaging/example/android/build.gradle
  packages/firebase_messaging/firebase_messaging/example/android/build.gradle
  packages/firebase_ml_custom/android/build.gradle
  packages/firebase_ml_custom/example/android/build.gradle
  packages/firebase_ml_vision/android/build.gradle
  packages/firebase_ml_vision/example/android/build.gradle
  packages/firebase_performance/android/build.gradle
  packages/firebase_performance/example/android/build.gradle
  packages/firebase_remote_config/README.md
  packages/firebase_remote_config/android/build.gradle
  packages/firebase_remote_config/example/android/build.gradle
  packages/firebase_storage/firebase_storage/android/build.gradle
  packages/firebase_storage/firebase_storage/example/android/build.gradle
Labels: cla: yes

#4257 docs(CONTRIBUTING): note that clang-format is needed
  CONTRIBUTING.md
Labels: cla: yes
