Repository firebase/flutterfire, pull requests merged in 2020-06, with the labels that each got.

#2572 [firebase_analytics] Wire the platform interface.
  packages/firebase_analytics/firebase_analytics/CHANGELOG.md
  packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
Labels: cla: yes

#2595 docs: sync updates
  docs/auth/overview.mdx
  docs/auth/phone.mdx
  docs/auth/social.mdx
  docs/auth/usage.mdx
  docs/core/usage.mdx
  docs/firestore/overview.mdx
  docs/firestore/usage.mdx
  docs/installation/android.mdx
  docs/installation/ios.mdx
  docs/installation/web.mdx
  docs/overview.mdx
  docs/versions.js
  website/docusaurus-plugins/source-api-reference.js
  website/docusaurus-plugins/source-versions.js
  website/docusaurus.config.js
  website/package.json
  website/src/pages/index.tsx
  website/src/plugins.js
  website/src/styles.scss
  website/src/theme/MDXComponents/index.tsx
  website/yarn.lock
Labels: cla: no

#2744 @ehesp/docs memory fix
  docs/auth/usage.mdx
  website/docusaurus-plugins/source-api-reference.js
  website/package.json
  website/src/pages/styles.module.scss
  website/src/styles.scss
  website/src/theme/MDXComponents/index.tsx
  website/src/theme/MDXComponents/styles.module.scss
Labels: cla: yes

#2773 docs: @ehesp/update docs url
  website/docusaurus.config.js
  website/static/CNAME
Labels: cla: yes

#2573 [firebase_analytics_web] Add initial implementation for firebase_analytics_web
  packages/firebase_analytics/firebase_analytics_web/.gitignore
  packages/firebase_analytics/firebase_analytics_web/.metadata
  packages/firebase_analytics/firebase_analytics_web/CHANGELOG.md
  packages/firebase_analytics/firebase_analytics_web/LICENSE
  packages/firebase_analytics/firebase_analytics_web/README.md
  packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
  packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_web/test/firebase_analytics_web_test.dart
Labels: cla: yes

#2787 Update Readme to use runZonedGuarded
  packages/firebase_crashlytics/README.md
Labels: cla: yes

#2785 Update readme with correct link for config steps
  packages/firebase_analytics/firebase_analytics/README.md
Labels: cla: yes

#2733 [cloud_firestore] Clean up Android Firestore listeners
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
Labels: cla: yes, plugin: cloud_firestore

#2862 [firebase_analytics] Disable expectation that breaks in flutter master.
  packages/firebase_analytics/firebase_analytics/test/observer_test.dart
Labels: cla: yes

#2859 [remote_config] Propagate native error message on #fetch
  packages/firebase_remote_config/CHANGELOG.md
  packages/firebase_remote_config/lib/src/remote_config.dart
  packages/firebase_remote_config/pubspec.yaml
Labels: cla: yes

#2844 [firebase_analytics_web] Add missing iOS files
  packages/firebase_analytics/firebase_analytics_web/CHANGELOG.md
  packages/firebase_analytics/firebase_analytics_web/ios/firebase_analytics_web.podspec
  packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
Labels: cla: yes

#107 [firebase_crashlytics] Use current stacktrace when null
  packages/firebase_crashlytics/CHANGELOG.md
  packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
  packages/firebase_crashlytics/pubspec.yaml
  packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
Labels: cla: yes
