Repository firebase/flutterfire, pull requests merged in 2020-07, with the labels that each got.

#109 [firebase_crashlytics] Add documentation on installing an error listener on Isolate
  packages/firebase_crashlytics/README.md
Labels: cla: yes

#2817 [dynamic_links]: fix initialization process
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/README.md
  packages/firebase_dynamic_links/example/lib/main.dart
  packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m
  packages/firebase_dynamic_links/pubspec.yaml
Labels: cla: yes

#2880 Phone auth fix
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/darwin/Classes/FLTFirebaseAuthPlugin.m
  packages/firebase_auth/firebase_auth/pubspec.yaml
Labels: cla: no

#146 [FirebasAuth] added that Errors are thrown via a PlatformException
  packages/firebase_auth/firebase_auth/README.md
Labels: cla: yes

#2883 [firebase_analytics] Add Firebase_Analytics Web to readme
  README.md
Labels: cla: yes

#184 Update README to describe supported authentication methods
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/README.md
  packages/firebase_auth/firebase_auth/pubspec.yaml
Labels: cla: yes

#2650 fix crash where listeners are not removed when app quits
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
Labels: cla: yes

#227 [flutter-messaging] fix notifications disappearing after app launch
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Labels: cla: yes

#2900 fix(core,macos): don't use umbrella Firebase header
  packages/firebase_core/firebase_core/ios/Classes/FLTFirebasePlugin.h
Labels: cla: yes

#2901 docs(messaging): update readme
  packages/firebase_messaging/README.md
Labels: cla: yes

#2916 chore(firebase_core): remove dependency on 'universal_platform'
  packages/firebase_core/firebase_core_platform_interface/lib/firebase_core_platform_interface.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_core_exceptions.dart
  packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
Labels: cla: yes

#2919 fix(cloud_firestore): remove get-write validation
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_transaction.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/method_channel_tests/method_channel_transaction_test.dart
Labels: cla: yes

#2924 docs: add auth updates
  docs/auth/error-handling.mdx
  docs/auth/phone.mdx
  docs/auth/social.mdx
  docs/auth/usage.mdx
  docs/installation/android.mdx
  docs/installation/web.mdx
  docs/overview.mdx
  docs/sidebars.js
  website/docusaurus.config.js
  website/src/pages/index.tsx
  website/src/pages/styles.module.scss
  website/src/theme/MDXComponents/index.tsx
  website/yarn.lock
Labels: cla: no

#2929 fix(firestore): normalize Firestore pointer path
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/internal/pointer.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/internal_tests/pointer_test.dart
Labels: cla: yes

#2907 chore(firebase_core): bump core versions
  packages/firebase_core/firebase_core/CHANGELOG.md
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md
  packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
  packages/firebase_core/firebase_core_web/CHANGELOG.md
  packages/firebase_core/firebase_core_web/pubspec.yaml
Labels: cla: yes

#2282 docs(cloud_firestore): fix example dir path in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#2692 docs(firebase_dynamic_links): update readme with up-to-date info
  packages/firebase_dynamic_links/README.md
Labels: cla: yes

#2869 [firebase_ml] Core android functionality
  packages/firebase_ml/android/build.gradle
  packages/firebase_ml/android/settings.gradle
  packages/firebase_ml/android/src/main/AndroidManifest.xml
  packages/firebase_ml/android/src/main/java/io/flutter/plugins/firebaseml/FirebaseMLPlugin.java
  packages/firebase_ml/android/src/main/java/io/flutter/plugins/firebaseml/FlutterFirebaseAppRegistrar.java
  packages/firebase_ml/android/src/main/java/io/flutter/plugins/firebaseml/ModelManager.java
  packages/firebase_ml/android/user-agent.gradle
  packages/firebase_ml/example/android/app/build.gradle
  packages/firebase_ml/example/android/app/google-services.json
  packages/firebase_ml/example/android/app/src/androidTest/java/io/flutter/plugins/firebaseml_example/EmbeddingV1ActivityTest.java
  packages/firebase_ml/example/android/app/src/androidTest/java/io/flutter/plugins/firebaseml_example/MainActivityTest.java
  packages/firebase_ml/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_ml/example/android/app/src/main/java/io/flutter/plugins/firebaseml_example/EmbeddingV1Activity.java
  packages/firebase_ml/example/android/app/src/main/java/io/flutter/plugins/firebaseml_example/MainActivity.java
  packages/firebase_ml/example/android/build.gradle
  packages/firebase_ml/example/android/settings.gradle
  packages/firebase_ml/example/assets/labels_mobilenet_v1_224.txt
  packages/firebase_ml/example/lib/main.dart
  packages/firebase_ml/example/pubspec.yaml
  packages/firebase_ml/example/test/widget_test.dart
  packages/firebase_ml/example/test_driver/firebase_ml.dart
  packages/firebase_ml/example/test_driver/firebase_ml_test.dart
  packages/firebase_ml/example/test_driver/firebase_model_manager.dart
  packages/firebase_ml/ios/Classes/FirebaseMLPlugin.m
  packages/firebase_ml/lib/firebase_ml.dart
  packages/firebase_ml/lib/src/firebase_ml.dart
  packages/firebase_ml/lib/src/model_management/firebase_model_download_conditions.dart
  packages/firebase_ml/lib/src/model_management/firebase_model_manager.dart
  packages/firebase_ml/lib/src/model_management/firebase_remote_model.dart
  packages/firebase_ml/pubspec.yaml
  packages/firebase_ml/test/firebase_ml_test.dart
  packages/firebase_ml/test/firebaseml_test.dart
Labels: cla: yes

#2930 docs: rework plugins table + add logo assets & roadmap link
  README.md
  website/static/img/flutterfire.svg
  website/static/img/flutterfire_1200x.png
  website/static/img/flutterfire_300x.png
  website/static/img/flutterfire_600x.png
Labels: cla: yes

#2942 tests(cloud_firestore): add additional equality tests
  packages/cloud_firestore/cloud_firestore/test/collection_reference_test.dart
  packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart
Labels: cla: yes

#2944 docs: add logo to overview
  docs/overview.mdx
  website/docusaurus.config.js
  website/src/pages/index.tsx
  website/src/theme/MDXComponents/index.tsx
Labels: cla: yes

#2945 fix(firestore): add timestamp tests & fix
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/timestamp.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
Labels: cla: yes

#2943 chore(release): prerelease cloud_firestore* packages
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
Labels: cla: yes

#2946 docs(auth): add missing import statement for google sign-in
  packages/firebase_auth/firebase_auth/README.md
Labels: cla: yes

#2948 Remove unused CI bits
  .ci/Dockerfile
  .cirrus.yml
  script/build_all_plugins_app.sh
  script/check_publish.sh
  script/common.sh
  script/incremental_build.sh
  script/lint_darwin_plugins.sh
Labels: cla: yes

#2947 tests(cloud_firestore): add unique query test path
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
Labels: cla: yes

#2952 tests(cloud_firestore): add unique query test path (2)
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
Labels: cla: yes

#2951 chore: migrate functions to use new core plugin
  packages/cloud_functions/cloud_functions/CHANGELOG.md
  packages/cloud_functions/cloud_functions/pubspec.yaml
  packages/cloud_functions/cloud_functions_platform_interface/CHANGELOG.md
  packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml
  packages/cloud_functions/cloud_functions_web/CHANGELOG.md
  packages/cloud_functions/cloud_functions_web/pubspec.yaml
Labels: cla: yes

#2931 fix(firestore): collection and document equality checking
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_collection_reference.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/platform_interface_tests/platform_interface_collection_reference_test.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/platform_interface_tests/platform_interface_document_reference_test.dart
Labels: cla: yes

#2959 docs: use latest plugin versions
  docs/auth/social.mdx
  docs/firestore/overview.mdx
  docs/firestore/usage.mdx
  docs/versions.js
  website/api.js
  website/docusaurus-plugins/source-api-reference.js
  website/docusaurus-plugins/source-versions.js
  website/docusaurus.config.js
  website/src/theme/MDXComponents/index.tsx
Labels: cla: yes

#2961 docs(cloud_firestore): update changelog
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
Labels: cla: yes

#2962 docs: fix readme typos
  README.md
  packages/cloud_firestore/cloud_firestore/README.md
  packages/cloud_functions/cloud_functions/README.md
  packages/firebase_admob/README.md
  packages/firebase_analytics/firebase_analytics/README.md
  packages/firebase_auth/firebase_auth/README.md
  packages/firebase_core/firebase_core/README.md
  packages/firebase_crashlytics/README.md
  packages/firebase_database/README.md
  packages/firebase_dynamic_links/README.md
  packages/firebase_in_app_messaging/README.md
  packages/firebase_messaging/README.md
  packages/firebase_ml_vision/README.md
  packages/firebase_performance/README.md
  packages/firebase_remote_config/README.md
  packages/firebase_storage/README.md
Labels: cla: yes, type: documentation

#2966 [cloud_firestore] Allow iOS and macOS to be imported as a module
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec
  packages/cloud_firestore/cloud_firestore/macos/cloud_firestore.podspec
Labels: cla: yes, platform: ios, platform: macos, plugin: cloud_firestore

#2967 feat(firebase_core): allow iOS/macOS to be imported as a module
  packages/firebase_core/firebase_core/CHANGELOG.md
  packages/firebase_core/firebase_core/ios/firebase_core.podspec
  packages/firebase_core/firebase_core/macos/firebase_core.podspec
  packages/firebase_core/firebase_core/pubspec.yaml
Labels: cla: yes, platform: ios, platform: macos, plugin: core

#2984 chore(cloud_firestore): remove analysis_options and fix warnings
  packages/cloud_firestore/cloud_firestore/analysis_options.yaml
  packages/cloud_firestore/cloud_firestore/example/lib/main.dart
  packages/cloud_firestore/cloud_firestore/example/run-tests-web
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_change_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/instance_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_change.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/write_batch.dart
Labels: cla: yes

#2958 fix(cloud_firestore): throw FirebaseException on web errors
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
Labels: cla: yes

#2986 chore(firebase_storage): migrate to depend on new `firebase_core` plugin
  .github/workflows/firebase_storage.yaml
  docs/sidebars.js
  docs/storage/overview.mdx
  docs/storage/usage.mdx
  packages/firebase_storage/CHANGELOG.md
  packages/firebase_storage/android/build.gradle
  packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
  packages/firebase_storage/darwin/Classes/FLTFirebaseStoragePlugin.m
  packages/firebase_storage/example/android/app/src/androidTest/java/io/flutter/plugins/firebasestorageexample/MainActivityTest.java
  packages/firebase_storage/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_storage/example/android/app/src/main/java/io/flutter/plugins/firebasestorageexample/EmbeddingV1Activity.java
  packages/firebase_storage/example/android/app/src/main/java/io/flutter/plugins/firebasestorageexample/MainActivity.java
  packages/firebase_storage/example/android/build.gradle
  packages/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.h
  packages/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
  packages/firebase_storage/ios/firebase_storage.podspec
  packages/firebase_storage/macos/Classes/FLTFirebaseStoragePlugin.m
  packages/firebase_storage/macos/firebase_storage.podspec
  packages/firebase_storage/pubspec.yaml
Labels: cla: yes

#2964 [firebase_dynamic_links]: fix plugin crash when link is null
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
  packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
Labels: cla: yes

#2996 chore(firebase_storage): fix false positive tests output
  .github/workflows/firebase_storage.yaml
  packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
  packages/firebase_storage/example/test_driver/firebase_storage.dart
  packages/firebase_storage/example/test_driver/firebase_storage_e2e.dart
  packages/firebase_storage/example/test_driver/firebase_storage_e2e_test.dart
  packages/firebase_storage/example/test_driver/firebase_storage_test.dart
Labels: cla: yes

#3001 tests(cloud_firestore): setup Firestore emulator
  .github/workflows/firebase_firestore.yaml
  .github/workflows/scripts/.firebaserc
  .github/workflows/scripts/firebase.json
  .github/workflows/scripts/firestore.rules
  .github/workflows/scripts/reset-firestore-emulator.sh
  .github/workflows/scripts/start-firestore-emulator.sh
  .gitignore
  packages/cloud_firestore/cloud_firestore/example/firebase.json
  packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/transaction_e2e.dart
Labels: cla: yes

#3006 chore(firebase_auth): migrate to depend on new `firebase_core` plugin
  docs/auth/overview.mdx
  docs/sidebars.js
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/android/build.gradle
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/darwin/Classes/FLTFirebaseAuthPlugin.m
  packages/firebase_auth/firebase_auth/example/android/build.gradle
  packages/firebase_auth/firebase_auth/example/lib/main.dart
  packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e.dart
  packages/firebase_auth/firebase_auth/ios/firebase_auth.podspec
  packages/firebase_auth/firebase_auth/macos/firebase_auth.podspec
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_auth/firebase_auth_web/CHANGELOG.md
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
Labels: cla: yes

#3010 [firebase_ml_vision] Bug fix: if confidence is 1 or 0 it is decoded as int
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/lib/src/image_labeler.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
  packages/firebase_ml_vision/test/image_labeler_test.dart
Labels: cla: yes

#3019 fix(cloud_firestore): remove unnecessary `await` in the example
  packages/cloud_firestore/cloud_firestore/example/lib/main.dart
Labels: cla: yes

#3011 chore(cloud_functions): migrate to depend on new `firebase_core` plugin
  .github/workflows/firebase_functions.yaml
  docs/functions/overview.mdx
  docs/sidebars.js
  packages/cloud_functions/cloud_functions/CHANGELOG.md
  packages/cloud_functions/cloud_functions/android/build.gradle
  packages/cloud_functions/cloud_functions/darwin/Classes/CloudFunctionsPlugin.m
  packages/cloud_functions/cloud_functions/example/android/app/src/main/AndroidManifest.xml
  packages/cloud_functions/cloud_functions/example/android/app/src/main/java/io/flutter/plugins/firebase/cloudfunctions/cloudfunctionsexample/EmbeddingV1Activity.java
  packages/cloud_functions/cloud_functions/example/android/app/src/main/java/io/flutter/plugins/firebase/cloudfunctions/cloudfunctionsexample/MainActivity.java
  packages/cloud_functions/cloud_functions/example/lib/main.dart
  packages/cloud_functions/cloud_functions/ios/cloud_functions.podspec
  packages/cloud_functions/cloud_functions/macos/cloud_functions.podspec
  packages/cloud_functions/cloud_functions/pubspec.yaml
Labels: cla: yes

#2950 [firebase_ml] Added IOS support (part 1)
  packages/firebase_ml/example/ios/Podfile
  packages/firebase_ml/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_ml/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/firebase_ml/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  packages/firebase_ml/example/ios/Runner/GoogleService-Info.plist
  packages/firebase_ml/example/ios/Runner/Info.plist
  packages/firebase_ml/example/pubspec.yaml
  packages/firebase_ml/ios/Classes/FLTFirebaseMLPlugin.h
  packages/firebase_ml/ios/Classes/FLTFirebaseMLPlugin.m
  packages/firebase_ml/ios/Classes/FLTModelManager.m
  packages/firebase_ml/ios/Classes/FirebaseMLPlugin.h
  packages/firebase_ml/ios/Classes/FirebaseMLPlugin.m
  packages/firebase_ml/ios/firebase_ml.podspec
  packages/firebase_ml/pubspec.yaml
Labels: cla: yes

#3034 [firebase-ml] READMEs for the plugin
  packages/firebase_ml/README.md
  packages/firebase_ml/example/README.md
Labels: cla: yes

#3040 Update user_info.dart
  packages/firebase_auth/firebase_auth/lib/src/user_info.dart
Labels: cla: no

#3038 chore(firebase_performance): migrate to depend on new `firebase_core` plugin
  .github/workflows/firebase_performance.yaml
  .gitignore
  docs/performance/overview.mdx
  docs/sidebars.js
  packages/firebase_performance/CHANGELOG.md
  packages/firebase_performance/android/build.gradle
  packages/firebase_performance/example/android/app/src/androidTest/java/io/flutter/plugins/firebaseperformance/EmbeddingV1ActivityTest.java
  packages/firebase_performance/example/android/app/src/androidTest/java/io/flutter/plugins/firebaseperformance/MainActivityTest.java
  packages/firebase_performance/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_performance/example/android/app/src/main/java/io/flutter/plugins/firebaseperformanceexample/EmbeddingV1Activity.java
  packages/firebase_performance/example/android/app/src/main/java/io/flutter/plugins/firebaseperformanceexample/MainActivity.java
  packages/firebase_performance/example/android/build.gradle
  packages/firebase_performance/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_performance/example/ios/Runner/GoogleService-Info.plist
  packages/firebase_performance/example/test_driver/firebase_performance.dart
  packages/firebase_performance/example/test_driver/firebase_performance_e2e.dart
  packages/firebase_performance/example/test_driver/firebase_performance_e2e_test.dart
  packages/firebase_performance/example/test_driver/firebase_performance_test.dart
  packages/firebase_performance/ios/Classes/FLTFirebasePerformancePlugin.m
  packages/firebase_performance/ios/firebase_performance.podspec
  packages/firebase_performance/pubspec.yaml
Labels: cla: yes, plugin: performance

#2969 [cloud_functions] Fix callable parameter type support on Android
  AUTHORS
  packages/cloud_functions/cloud_functions/CHANGELOG.md
  packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/CloudFunctionsPlugin.java
Labels: cla: yes

#2940 [firebase-auth] handles FIRAuthErrorCodeTooManyRequests on iOS
  packages/firebase_auth/firebase_auth/darwin/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#3036 [firebase_ml_custom] Interface changes and cleanup
  packages/firebase_ml/android/src/main/java/io/flutter/plugins/firebaseml/ModelManager.java
  packages/firebase_ml/example/ios/Podfile
  packages/firebase_ml/example/lib/main.dart
  packages/firebase_ml/example/test_driver/firebase_ml.dart
  packages/firebase_ml/example/test_driver/firebase_model_manager.dart
  packages/firebase_ml/ios/Classes/FLTModelManager.m
  packages/firebase_ml/lib/src/model_management/firebase_model_download_conditions.dart
  packages/firebase_ml/lib/src/model_management/firebase_model_manager.dart
  packages/firebase_ml/lib/src/model_management/firebase_remote_model.dart
  packages/firebase_ml/test/firebase_ml_test.dart
Labels: cla: yes

#3047 chore: update e2e version & add CI scripts
  .github/workflows/firebase_functions.yaml
  .github/workflows/scripts/build-example.sh
  .github/workflows/scripts/drive-example.sh
  .github/workflows/scripts/install-flutter.sh
  .github/workflows/scripts/install-tools.sh
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_functions/cloud_functions/example/pubspec.yaml
  packages/firebase_admob/example/pubspec.yaml
  packages/firebase_admob/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/example/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_core/firebase_core/example/pubspec.yaml
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_crashlytics/example/pubspec.yaml
  packages/firebase_crashlytics/pubspec.yaml
  packages/firebase_database/example/pubspec.yaml
  packages/firebase_database/pubspec.yaml
  packages/firebase_dynamic_links/example/pubspec.yaml
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_messaging/example/pubspec.yaml
  packages/firebase_messaging/pubspec.yaml
  packages/firebase_ml_vision/example/pubspec.yaml
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_performance/example/pubspec.yaml
  packages/firebase_performance/pubspec.yaml
  packages/firebase_remote_config/example/pubspec.yaml
  packages/firebase_remote_config/pubspec.yaml
  packages/firebase_storage/example/pubspec.yaml
  packages/firebase_storage/pubspec.yaml
Labels: cla: yes

#3060 tests: update CI workflows to use new scripts
  .github/workflows/firebase_auth.yaml
  .github/workflows/firebase_core.yaml
  .github/workflows/firebase_database.yaml
  .github/workflows/firebase_firestore.yaml
  .github/workflows/firebase_performance.yaml
  .github/workflows/firebase_storage.yaml
  .github/workflows/scripts/drive-example.sh
  README.md
  website/plugins.js
Labels: cla: yes

#3062 docs(cloud_firestore): update usage examples
  docs/core/usage.mdx
  docs/firestore/usage.mdx
Labels: cla: yes

#3071 chore(firebase_messaging): migrate to depend on new `firebase_core` plugin
  .github/workflows/firebase_messaging.yaml
  docs/messaging/overview.mdx
  docs/sidebars.js
  packages/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/android/build.gradle
  packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
  packages/firebase_messaging/example/android/app/src/main/java/io/flutter/plugins/firebasemessagingexample/MainActivity.java
  packages/firebase_messaging/example/pubspec.yaml
  packages/firebase_messaging/example/test_driver/firebase_messaging_e2e.dart
  packages/firebase_messaging/example/test_driver/firebase_messaging_e2e_test.dart
  packages/firebase_messaging/example/test_driver/firebase_messaging_test.dart
  packages/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
  packages/firebase_messaging/ios/firebase_messaging.podspec
  packages/firebase_messaging/pubspec.yaml
  packages/firebase_messaging/test/firebase_messaging_e2e.dart
Labels: cla: yes
