Repository firebase/flutterfire, pull requests merged in 2020-10, with the labels that each got.

#3717 docs: updating document to proper doc reference
  docs/firestore/usage.mdx
Labels: cla: no

#3699 docs: update section on Android package name
  AUTHORS
  docs/installation/android.mdx
Labels: cla: yes

#3693 docs: fix typo in getting started guide
  docs/overview.mdx
Labels: cla: yes

#3728 docs: remove `updateBlock` reference in Firestore docs
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
Labels: cla: yes

#3452 fix(cloud_firestore): remove listener if available
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
Labels: cla: yes

#3603 docs: fix typo in the documentation of firebase_ml_vision
  packages/firebase_ml_vision/README.md
Labels: cla: yes

#3729 fix: remove `platform` package usage
  packages/firebase_admob/pubspec.yaml
  packages/firebase_messaging/lib/firebase_messaging.dart
  packages/firebase_messaging/pubspec.yaml
  packages/firebase_messaging/test/firebase_messaging_test.dart
Labels: cla: yes

#3655 fix(docs): typo in code comments
  AUTHORS
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/set_options.dart
Labels: cla: yes

#3713 fix(cloud_firestore_web): fix dependency in pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
Labels: blocked: do-not-merge, cla: yes

#3731 fix(firebase_auth): Optional params for "signInWithCredential" method are converted to "nil" if "null" for iOS
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#2963 chore: update contributing file
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: cla: yes, type: documentation

#3734 fix: dependency issue in pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
Labels: cla: yes

#3456 docs(auth): added named argument labels.
  docs/auth/phone.mdx
Labels: cla: yes

#3739 Contributing file: Fix outdated url
  CONTRIBUTING.md
Labels: cla: yes

#3744 Delete package_config.json
  packages/firebase_storage/firebase_storage/package_config.json
Labels: cla: yes

#3753 docs(firebase_crashlytics): corrects plugin apply location
  docs/crashlytics/overview.mdx
Labels: cla: yes

#3768 docs: README updates
  docs/storage/usage.mdx
  packages/firebase_auth/firebase_auth/README.md
  packages/firebase_crashlytics/firebase_crashlytics/README.md
  packages/firebase_storage/firebase_storage/README.md
Labels: cla: yes

#3686 fix(firebase_auth): on iOS use sendEmailVerificationWithActionCodeSettings instead of sendEmailVerificationWithCompletion
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#3774 docs(firebase_storage): fix broken link in documentation
  docs/storage/usage.mdx
Labels: cla: yes

#3772 fix(cloud_firestore): ensure isCollectionGroupQuery is initialised
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
Labels: cla: yes

#3763 docs(firebase_crashlytics): Update the example image in docs
  docs/_assets/crashlytics-example-detail.png
Labels: cla: yes

#3747 fix(cloud_firestore): fix returning of transaction result
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
Labels: cla: yes

#3584 docs: updated flutter_facebook_auth version
  docs/versions.js
Labels: cla: yes

#3639 fix(firebase_crashlytics): Change minimum version of stack_trace package
  packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
Labels: cla: yes

#3443 docs(firebase_auth): remove use of toString() on error
  docs/auth/usage.mdx
Labels: cla: yes

#3611 fix: remove unused dart:async import
  packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_core/firebase_core/lib/firebase_core.dart
Labels: blocked: do-not-merge, cla: yes

#3726 fix(firebase_storage): bubble exceptions
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_reference.dart
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/utils/exception.dart
Labels: cla: yes

#3701 fix(cloud_firestore): bubble exceptions
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_write_batch.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/exception.dart
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
Labels: cla: yes

#3788 docs(firebase_storage): fix TaskState typo in docs
  docs/storage/usage.mdx
Labels: cla: yes

#3737 fix(firebase_auth): fix firebase_auth listeners assigning of currentUser
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart
Labels: cla: yes

#3957 feat: update native Firebase SDK dependencies for Android & iOS
  packages/cloud_firestore/cloud_firestore/example/ios/Podfile
  packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec
  packages/cloud_firestore/cloud_firestore/macos/cloud_firestore.podspec
  packages/cloud_functions/cloud_functions/ios/cloud_functions.podspec
  packages/cloud_functions/cloud_functions/macos/cloud_functions.podspec
  packages/firebase_admob/ios/firebase_admob.podspec
  packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec
  packages/firebase_auth/firebase_auth/ios/firebase_auth.podspec
  packages/firebase_auth/firebase_auth/macos/firebase_auth.podspec
  packages/firebase_core/firebase_core/android/gradle.properties
  packages/firebase_core/firebase_core/ios/firebase_core.podspec
  packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
  packages/firebase_core/firebase_core/macos/firebase_core.podspec
  packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec
  packages/firebase_crashlytics/firebase_crashlytics/macos/firebase_crashlytics.podspec
  packages/firebase_database/ios/firebase_database.podspec
  packages/firebase_database/macos/firebase_database.podspec
  packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec
  packages/firebase_in_app_messaging/ios/firebase_in_app_messaging.podspec
  packages/firebase_messaging/ios/firebase_messaging.podspec
  packages/firebase_performance/example/android/app/build.gradle
  packages/firebase_performance/ios/firebase_performance.podspec
  packages/firebase_remote_config/ios/firebase_remote_config.podspec
  packages/firebase_remote_config/macos/firebase_remote_config.podspec
  packages/firebase_storage/firebase_storage/ios/firebase_storage.podspec
  packages/firebase_storage/firebase_storage/macos/firebase_storage.podspec
Labels: cla: yes

#3943 docs(firebase_auth): add steps for Email Link Authentication
  docs/auth/usage.mdx
Labels: cla: yes

#3945 docs(auth): update to credential to use object notation
  docs/auth/usage.mdx
Labels: cla: yes

#3567 fix(ios,dynamic_links): fixed issue with overwriting correct url with null one
  packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m
Labels: cla: yes, plugin: dynamic_links

#3891 docs(firebase_auth): fix broken links
  docs/auth/usage.mdx
Labels: cla: yes

#3975 feat(android): bump compileSdkVersion to 29
  packages/cloud_firestore/cloud_firestore/android/build.gradle
  packages/cloud_firestore/cloud_firestore/example/android/app/build.gradle
  packages/cloud_functions/cloud_functions/android/build.gradle
  packages/cloud_functions/cloud_functions/example/android/app/build.gradle
  packages/firebase_admob/android/build.gradle
  packages/firebase_admob/example/android/app/build.gradle
  packages/firebase_analytics/firebase_analytics/android/build.gradle
  packages/firebase_analytics/firebase_analytics/example/android/app/build.gradle
  packages/firebase_auth/firebase_auth/android/build.gradle
  packages/firebase_auth/firebase_auth/example/android/app/build.gradle
  packages/firebase_core/firebase_core/android/build.gradle
  packages/firebase_core/firebase_core/example/android/app/build.gradle
  packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle
  packages/firebase_crashlytics/firebase_crashlytics/example/android/app/build.gradle
  packages/firebase_database/android/build.gradle
  packages/firebase_database/example/android/app/build.gradle
  packages/firebase_dynamic_links/android/build.gradle
  packages/firebase_dynamic_links/example/android/app/build.gradle
  packages/firebase_in_app_messaging/android/build.gradle
  packages/firebase_in_app_messaging/example/android/app/build.gradle
  packages/firebase_messaging/android/build.gradle
  packages/firebase_messaging/example/android/app/build.gradle
  packages/firebase_ml_custom/android/build.gradle
  packages/firebase_ml_custom/example/android/app/build.gradle
  packages/firebase_ml_vision/android/build.gradle
  packages/firebase_ml_vision/example/android/app/build.gradle
  packages/firebase_performance/android/build.gradle
  packages/firebase_performance/example/android/app/build.gradle
  packages/firebase_remote_config/android/build.gradle
  packages/firebase_remote_config/example/android/app/build.gradle
  packages/firebase_storage/firebase_storage/android/build.gradle
  packages/firebase_storage/firebase_storage/example/android/app/build.gradle
Labels: cla: yes
