Repository firebase/flutterfire, pull requests merged in 2020-08, with the labels that each got.

#3096 [firebase_auth] Update example in Auth to use new core
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/pubspec.yaml
Labels: cla: yes

#3104 Add disclaimer
  README.md
Labels: cla: yes

#3094 [Firebase_auth] Text says register instead of sign in auth example
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
Labels: cla: yes

#3107 Use firebase hosting
  .github/workflows/docs.yaml
  website/.firebaserc
  website/.gitignore
  website/firebase.json
Labels: cla: yes

#3093 [firebase_ml_vision] Text recognition in documents through DocumentTextRecognizer
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/README.md
  packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/DocumentTextRecognizer.java
  packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/FirebaseMlVisionHandler.java
  packages/firebase_ml_vision/example/lib/camera_preview_scanner.dart
  packages/firebase_ml_vision/example/lib/detector_painters.dart
  packages/firebase_ml_vision/example/lib/picture_scanner.dart
  packages/firebase_ml_vision/example/test_driver/document_text_recognizer.dart
  packages/firebase_ml_vision/example/test_driver/firebase_ml_vision.dart
  packages/firebase_ml_vision/ios/Classes/DocumentTextRecognizer.m
  packages/firebase_ml_vision/ios/Classes/FLTFirebaseMlVisionPlugin.h
  packages/firebase_ml_vision/ios/Classes/FLTFirebaseMlVisionPlugin.m
  packages/firebase_ml_vision/lib/firebase_ml_vision.dart
  packages/firebase_ml_vision/lib/src/document_text_recognizer.dart
  packages/firebase_ml_vision/lib/src/firebase_vision.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/document_text_recognizer_test.dart
Labels: cla: yes

#3102 chore(firebase_in_app_messaging): migrate to new `firebase_core` plugin
  packages/firebase_in_app_messaging/CHANGELOG.md
  packages/firebase_in_app_messaging/android/build.gradle
  packages/firebase_in_app_messaging/android/src/main/AndroidManifest.xml
  packages/firebase_in_app_messaging/android/src/main/java/io/flutter/plugins/firebase/inappmessaging/FirebaseInAppMessagingPlugin.java
  packages/firebase_in_app_messaging/example/android/app/src/androidTest/java/com/example/firebase_in_app_messaging/EmbeddingV1ActivityTest.java
  packages/firebase_in_app_messaging/example/android/app/src/androidTest/java/com/example/firebase_in_app_messaging/MainActivityTest.java
  packages/firebase_in_app_messaging/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_in_app_messaging/example/android/app/src/main/java/com/example/firebase_in_app_messaging_example/EmbeddingV1Activity.java
  packages/firebase_in_app_messaging/example/android/app/src/main/java/com/example/firebase_in_app_messaging_example/MainActivity.java
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_in_app_messaging/ios/firebase_in_app_messaging.podspec
  packages/firebase_in_app_messaging/pubspec.yaml
Labels: cla: yes

#3121 [firebase_ml_custom] Final adjustments before the initial release
  packages/firebase_ml_custom/example/README.md
  packages/firebase_ml_custom/example/android/app/google-services.json
  packages/firebase_ml_custom/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_ml_custom/example/ios/Runner/GoogleService-Info.plist
  packages/firebase_ml_custom/example/lib/main.dart
  packages/firebase_ml_custom/ios/firebase_ml_custom.podspec
Labels: cla: yes

#3138 docs: add migration guide
  docs/migration-guide.mdx
  docs/sidebars.js
Labels: cla: yes

#3106 [firebase_ml_vision] Options for Cloud TextRecognizer
  packages/firebase_ml_custom/example/lib/main.dart
  packages/firebase_ml_custom/example/pubspec.yaml
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/README.md
  packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/TextRecognizer.java
  packages/firebase_ml_vision/example/lib/picture_scanner.dart
  packages/firebase_ml_vision/example/pubspec.yaml
  packages/firebase_ml_vision/example/test_driver/text_recognizer.dart
  packages/firebase_ml_vision/ios/Classes/TextRecognizer.m
  packages/firebase_ml_vision/lib/src/firebase_vision.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
Labels: cla: yes

#3113 [firebase_ml_vision] Options for DocumentTextRecognizer
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/README.md
  packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/DocumentTextRecognizer.java
  packages/firebase_ml_vision/example/test_driver/document_text_recognizer.dart
  packages/firebase_ml_vision/ios/Classes/DocumentTextRecognizer.m
  packages/firebase_ml_vision/lib/src/document_text_recognizer.dart
  packages/firebase_ml_vision/lib/src/firebase_vision.dart
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/document_text_recognizer_test.dart
Labels: cla: yes

#3145 [firebase_ml_custom] Improved descriptions of the plugin and the initial commit
  README.md
  packages/firebase_ml_custom/CHANGELOG.md
  packages/firebase_ml_custom/pubspec.yaml
Labels: cla: yes

#3147 Bump firebase_auth_web dependency version
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/pubspec.yaml
Labels: cla: yes

#3149 [infra] Add direct trigger for docs workflow
  .github/workflows/docs.yaml
Labels: cla: yes

#3146 docs: replace outdated pub URLs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/auth/overview.mdx
  docs/functions/overview.mdx
  docs/overview.mdx
  packages/cloud_firestore/cloud_firestore/README.md
  packages/cloud_functions/cloud_functions/README.md
  packages/firebase_analytics/firebase_analytics/README.md
  packages/firebase_analytics/firebase_analytics/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/README.md
  packages/firebase_auth/firebase_auth/example/README.md
  packages/firebase_core/firebase_core/README.md
  packages/firebase_crashlytics/README.md
  packages/firebase_database/README.md
  packages/firebase_dynamic_links/README.md
  packages/firebase_in_app_messaging/README.md
  packages/firebase_messaging/README.md
  packages/firebase_ml_custom/README.md
  packages/firebase_ml_custom/example/README.md
  packages/firebase_ml_vision/CHANGELOG.md
  packages/firebase_ml_vision/README.md
  packages/firebase_ml_vision/example/README.md
  packages/firebase_performance/README.md
  packages/firebase_remote_config/README.md
  packages/firebase_storage/README.md
  website/api.js
  website/src/pages/index.tsx
Labels: cla: yes

#3158 refactor: remove signInSecondFactor
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/id_token_result.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/id_token_result_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_user_test.dart
Labels: cla: yes

#3160 docs: update docs
  docs/auth/error-handling.mdx
  docs/auth/overview.mdx
  docs/auth/phone.mdx
  docs/auth/social.mdx
  docs/auth/usage.mdx
  docs/firestore/usage.mdx
  docs/installation/android.mdx
  docs/installation/ios.mdx
  docs/migration-guide.mdx
Labels: cla: yes

#3143 docs: fixed typos
  packages/cloud_firestore/cloud_firestore/README.md
Labels: cla: yes

#3175 [docs] Add doc previews
  .github/workflows/docs_preview.yaml
  docs-preview/action.min.js
  docs-preview/action.yaml
Labels: cla: yes

#3110 [firebase_dynamic_links] migrate to new `firebase_core` plugin
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/android/build.gradle
  packages/firebase_dynamic_links/example/android/app/src/androidTest/java/io/flutter/plugins/firebasedynamiclinks/EmbeddingV1ActivityTest.java
  packages/firebase_dynamic_links/example/android/app/src/androidTest/java/io/flutter/plugins/firebasedynamiclinks/MainActivityTest.java
  packages/firebase_dynamic_links/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_dynamic_links/example/android/app/src/main/java/io/flutter/plugins/firebasedynamiclinksexample/EmbeddingV1Activity.java
  packages/firebase_dynamic_links/example/android/app/src/main/java/io/flutter/plugins/firebasedynamiclinksexample/MainActivity.java
  packages/firebase_dynamic_links/example/pubspec.yaml
  packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec
  packages/firebase_dynamic_links/pubspec.yaml
Labels: cla: yes

#3192 docs: fixed a typo in migration-guide.mdx
  docs/migration-guide.mdx
Labels: cla: yes

#3198 fix(cloud_firestore): web - remove encode on "where" delegate
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
Labels: cla: yes

#3200 fix(cloud_firestore): allow FieldPath.documentId as query field
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
Labels: cla: yes

#3180 fix(dynamic_links): podspec
  packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec
Labels: cla: yes

#3199 chore: remove android directory from web plugins
  packages/cloud_firestore/cloud_firestore_web/android/.gitignore
  packages/cloud_firestore/cloud_firestore_web/android/build.gradle
  packages/cloud_firestore/cloud_firestore_web/android/gradle.properties
  packages/cloud_firestore/cloud_firestore_web/android/gradle/wrapper/gradle-wrapper.properties
  packages/cloud_firestore/cloud_firestore_web/android/settings.gradle
  packages/cloud_firestore/cloud_firestore_web/android/src/main/AndroidManifest.xml
  packages/cloud_firestore/cloud_firestore_web/android/src/main/java/io/flutter/plugins/cloud_firestore_web/FirestoreWebPlugin.java
  packages/cloud_functions/cloud_functions_web/android/.gitignore
  packages/cloud_functions/cloud_functions_web/android/build.gradle
  packages/cloud_functions/cloud_functions_web/android/gradle.properties
  packages/cloud_functions/cloud_functions_web/android/gradle/wrapper/gradle-wrapper.properties
  packages/cloud_functions/cloud_functions_web/android/settings.gradle
  packages/cloud_functions/cloud_functions_web/android/src/main/AndroidManifest.xml
  packages/cloud_functions/cloud_functions_web/android/src/main/java/io/flutter/plugins/cloud_functions_web/CloudFunctionsWebPlugin.java
  packages/firebase_auth/firebase_auth_web/android/.gitignore
  packages/firebase_auth/firebase_auth_web/android/build.gradle
  packages/firebase_auth/firebase_auth_web/android/gradle.properties
  packages/firebase_auth/firebase_auth_web/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_auth/firebase_auth_web/android/settings.gradle
  packages/firebase_auth/firebase_auth_web/android/src/main/AndroidManifest.xml
  packages/firebase_auth/firebase_auth_web/android/src/main/java/io/flutter/plugins/firebaseauth_web/FirebaseAuthWebPlugin.java
  packages/firebase_core/firebase_core_web/android/.gitignore
  packages/firebase_core/firebase_core_web/android/build.gradle
  packages/firebase_core/firebase_core_web/android/gradle.properties
  packages/firebase_core/firebase_core_web/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_core/firebase_core_web/android/settings.gradle
  packages/firebase_core/firebase_core_web/android/src/main/AndroidManifest.xml
  packages/firebase_core/firebase_core_web/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java
Labels: cla: yes

#3202 docs: update android migration steps
  docs/migration-guide.mdx
Labels: cla: yes

#3207 docs(auth): fixed typo
  docs/auth/usage.mdx
Labels: cla: yes

#3204 fix(android): suppress warnings
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreTransactionHandler.java
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart
Labels: cla: yes

#3208 Replace forbidden branch name chars
  docs-preview/action.min.js
Labels: cla: yes

#3216 fix: documentation changes and google auth provider assert
  docs/auth/error-handling.mdx
  docs/auth/phone.mdx
  docs/auth/social.mdx
  docs/auth/usage.mdx
  docs/core/usage.mdx
  docs/firestore/usage.mdx
  docs/migration-guide.mdx
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/google_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/providers_tests/google_auth_test.dart
Labels: cla: yes

#3217 fix(auth,android): unknown error codes
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPluginException.java
Labels: cla: yes

#3214 fix(cloud_firestore): add FieldPathType check & tests
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
Labels: cla: yes

#3233 Update GitHub link of https://firebase.flutter.dev
  website/src/pages/index.tsx
Labels: cla: yes

#3234 fix(fiam): podspec missing variable
  packages/firebase_in_app_messaging/ios/firebase_in_app_messaging.podspec
Labels: cla: yes

#3230 docs: updated file path
  docs/auth/usage.mdx
  docs/firestore/usage.mdx
Labels: cla: yes

#3247 fix(cloud_firestore): encode "where" query values
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
Labels: cla: yes

#3248 docs: social auth docs fixes
  docs/auth/social.mdx
Labels: cla: yes

#3251 fix(cloud_firestore): prevent snapshot race conditions
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
Labels: cla: yes

#3256 docs: improve links readability in darkmode
  .github/docs-preview/action.min.js
  .github/docs-preview/action.yaml
  .github/workflows/docs_preview.yaml
  website/docusaurus.config.js
  website/src/styles.scss
Labels: cla: yes

#3257 fix(auth): add missing auth deprecations
  packages/firebase_auth/firebase_auth/lib/src/user.dart
Labels: cla: yes

#3258 chore: release 20-08-2020
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md
  packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
  packages/firebase_auth/firebase_auth_web/CHANGELOG.md
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
  packages/firebase_dynamic_links/CHANGELOG.md
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_in_app_messaging/CHANGELOG.md
  packages/firebase_in_app_messaging/pubspec.yaml
Labels: cla: yes

#3246 docs: add badges for Pub Points from pub.dev
  README.md
Labels: cla: yes

#3265 docs: added the missing catch for error handling
  docs/firestore/usage.mdx
Labels: cla: yes

#3322 [docs] Add Google Analytics to Docs
  website/docusaurus.config.js
Labels: cla: yes

#3326 chore: intellij cleanup
  melos.yaml
  packages/firebase_admob/example/android.iml
  packages/firebase_admob/example/firebase_admob_example.iml
  packages/firebase_admob/example/firebase_admob_example_android.iml
  packages/firebase_admob/firebase_admob_android.iml
  packages/firebase_analytics/firebase_analytics/example/android.iml
  packages/firebase_analytics/firebase_analytics/example/firebase_analytics_example.iml
  packages/firebase_core/firebase_core/firebase_core_android.iml
  packages/firebase_database/example/android.iml
  packages/firebase_database/example/firebase_database_example.iml
  packages/firebase_dynamic_links/example/firebase_dynamic_links_example.iml
  packages/firebase_dynamic_links/example/firebase_dynamic_links_example_android.iml
  packages/firebase_dynamic_links/firebase_dynamic_links_android.iml
  packages/firebase_messaging/android/android.iml
  packages/firebase_messaging/android/firebase_messaging.iml
  packages/firebase_messaging/example/android.iml
  packages/firebase_messaging/example/example.iml
  packages/firebase_messaging/example/firebase_messaging_example.iml
  packages/firebase_performance/example/firebase_performance_example.iml
  packages/firebase_performance/example/firebase_performance_example_android.iml
  packages/firebase_performance/firebase_performance_android.iml
  packages/firebase_remote_config/example/android.iml
  packages/firebase_remote_config/example/firebase_remote_config_example.iml
  packages/firebase_remote_config/example/firebase_remote_config_example_android.iml
  packages/firebase_remote_config/firebase_remote_config_android.iml
  packages/firebase_storage/example/android.iml
  packages/firebase_storage/example/firebase_storage_example.iml
Labels: cla: yes

#3330 [docs] Try gtag for docs analytics
  website/docusaurus.config.js
Labels: cla: yes

#3333 docs: corrected bad iOS pod version for Firebase SDK
  docs/overview.mdx
Labels: cla: yes

#3317 docs: mention non-specific method exception codes
  docs/auth/error-handling.mdx
Labels: cla: yes, type: documentation

#3316 fix(firebase_auth): use correct FIRAuth instance on for listeners
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes, platform: ios, plugin: auth

#3313 fix(firebase_auth): send userPlatform on changes
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
Labels: cla: yes, platform: web, plugin: auth

#3367 chore: update CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#3347 feat(firebase_admob): integrate Admob with new core
  .github/workflows/firebase_admob.yaml
  .github/workflows/scripts/build-example.sh
  .github/workflows/scripts/drive-example.sh
  .github/workflows/scripts/install-flutter.sh
  docs/migration-guide.mdx
  packages/firebase_admob/CHANGELOG.md
  packages/firebase_admob/android/build.gradle
  packages/firebase_admob/example/android/app/build.gradle
  packages/firebase_admob/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_admob/example/android/app/src/androidTest/java/io/flutter/plugins/firebaseadmob/EmbeddingV1ActivityTest.java
  packages/firebase_admob/example/android/app/src/androidTest/java/io/flutter/plugins/firebaseadmob/MainActivityTest.java
  packages/firebase_admob/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_admob/example/android/app/src/main/java/io/flutter/plugins/firebaseadmobexample/EmbeddingV1Activity.java
  packages/firebase_admob/example/android/app/src/main/java/io/flutter/plugins/firebaseadmobexample/MainActivity.java
  packages/firebase_admob/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_admob/example/pubspec.yaml
  packages/firebase_admob/ios/firebase_admob.podspec
  packages/firebase_admob/pubspec.yaml
Labels: cla: yes

#3314 docs: update initialization docs
  docs/overview.mdx
Labels: cla: yes, plugin: core, type: documentation

#3365 docs: add note about Firestore iOS build times
  docs/overview.mdx
Labels: cla: yes

#3342 docs: fixed signOut method documentation
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
Labels: cla: yes

#3360 fix(firebase_auth): update FLTFirebaseAuthPlugin.m
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#3345 fix(firebase_auth): use unknown APNS token type
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#3344 fix(firebase_auth): implement missing web confirmPasswordReset
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
Labels: cla: yes

#3320 fix(firebase_auth): force locale timestamp conversion
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web_user.dart
Labels: cla: yes, platform: web, plugin: auth

#3308 feat(firebase_auth): expose smsCode (android only)
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/phone_auth.dart
Labels: cla: yes, plugin: auth

#3318 fix: pub.dev score fixes
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/firebase_auth/firebase_auth/lib/src/user_credential.dart
Labels: cla: yes, plugin: auth, plugin: cloud_firestore

#3357 fix(firebase_auth): fix IdTokenResult timestamps (web, ios)
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/id_token_result.dart
  packages/firebase_auth/firebase_auth_web/lib/utils.dart
Labels: cla: yes

#3364 docs: update Firebase configuration naming
  docs/installation/android.mdx
  docs/installation/ios.mdx
  docs/installation/macos.mdx
  docs/installation/web.mdx
Labels: cla: yes

#3109 feat(database): implement support for `ServerValue.increment(delta)`
  packages/firebase_database/lib/src/database_reference.dart
  packages/firebase_database/test/firebase_database_test.dart
Labels: cla: yes, plugin: database, type: missing-feature

#3205 feat(firebase_auth): implement signInWithPhoneNumber on web
  docs/_assets/recaptcha-widget-inline.jpg
  docs/_assets/recaptcha-widget.jpg
  docs/auth/phone.mdx
  packages/firebase_auth/firebase_auth/lib/firebase_auth.dart
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
  packages/firebase_auth/firebase_auth/lib/src/recaptcha_verifier.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_recaptcha_verifier_factory.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/platform_interface_tests/platform_interface_recaptcha_verifier_factory_test.dart
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web_recaptcha_verifier_factory.dart
  packages/firebase_auth/firebase_auth_web/lib/utils.dart
Labels: cla: yes, platform: web, plugin: auth

#3269 feat(firebase_auth): use named arguments for ActionCodeSettings
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_settings.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/action_code_settings_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_user_test.dart
  packages/firebase_auth/firebase_auth_web/lib/utils.dart
Labels: cla: yes, plugin: auth

#3319 fix: local dependencies in example apps
  packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
  packages/cloud_functions/cloud_functions/example/pubspec.yaml
  packages/firebase_admob/example/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
  packages/firebase_database/example/pubspec.yaml
  packages/firebase_dynamic_links/example/pubspec.yaml
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_messaging/example/pubspec.yaml
  packages/firebase_ml_custom/example/pubspec.yaml
  packages/firebase_ml_vision/example/pubspec.yaml
  packages/firebase_performance/example/pubspec.yaml
  packages/firebase_remote_config/example/pubspec.yaml
  packages/firebase_storage/example/pubspec.yaml
Labels: cla: yes

#3116 chore: fix pod install error on example FIAM app
  packages/firebase_in_app_messaging/example/ios/Runner.xcodeproj/project.pbxproj
Labels: cla: yes

#3350 [docs] snapshot calls data
  docs/firestore/usage.mdx
Labels: cla: yes

#3387 feat(cloud_firestore): add a [] operator to DocumentSnapshot, acting as get()
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/test/document_snapshot_test.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_snapshot.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/platform_interface_tests/platform_interface_document_snapshot_test.dart
Labels: cla: yes

#3389 docs: update overview example
  docs/overview.mdx
Labels: cla: yes
