Repository firebase/flutterfire, pull requests merged in 2021-03, with the labels that each got.

#5148 docs: email verified behaviour when using the Facebook provider
  docs/auth/social.mdx
Labels: cla: yes

#5120 refactor: NNBD docs migration
  docs/analytics/overview.mdx
  docs/auth/overview.mdx
  docs/core/usage.mdx
  docs/crashlytics/overview.mdx
  docs/database/overview.mdx
  docs/firestore/overview.mdx
  docs/functions/overview.mdx
  docs/messaging/overview.mdx
  docs/null-safety.mdx
  docs/overview.mdx
  docs/performance/overview.mdx
  docs/remote-config/overview.mdx
  docs/storage/overview.mdx
  website/api.js
  website/package.json
  website/yarn.lock
Labels: cla: yes

#5203 docs: include deprecation plan and migration guide for firebase_admob to google_mobile_ads
  packages/firebase_admob/README.md
Labels: cla: yes

#5230 chore: apply lints on firebase_admob
  packages/firebase_admob/all_lint_rules.yaml
  packages/firebase_admob/analysis_options.yaml
  packages/firebase_admob/example/analysis_options.yaml
  packages/firebase_admob/example/lib/main.dart
  packages/firebase_admob/example/pubspec.yaml
  packages/firebase_admob/example/test_driver/firebase_admob.dart
  packages/firebase_admob/example/test_driver/firebase_admob_test.dart
  packages/firebase_admob/lib/firebase_admob.dart
  packages/firebase_admob/pubspec.yaml
  packages/firebase_admob/test/firebase_admob_e2e.dart
  packages/firebase_admob/test/firebase_admob_test.dart
Labels: cla: yes

#5221 chore: rm dev dependencies breaking CI
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_database/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
  packages/firebase_storage/firebase_storage/pubspec.yaml
Labels: cla: yes

#5168 docs(emulators): add instructions for firebase emulator suite networking
  docs/auth/usage.mdx
  docs/firestore/usage.mdx
  docs/functions/usage.mdx
  docs/installation/android.mdx
  docs/installation/ios.mdx
  docs/installation/macos.mdx
Labels: cla: yes

#5169 docs(auth, web): note that auth emulator is not supported for web
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
Labels: cla: yes

#5234 chore: enable lints on firebase_ml_vision
  packages/firebase_ml_vision/all_lint_rules.yaml
  packages/firebase_ml_vision/analysis_options.yaml
  packages/firebase_ml_vision/example/analysis_options.yaml
  packages/firebase_ml_vision/example/lib/camera_preview_scanner.dart
  packages/firebase_ml_vision/example/lib/detector_painters.dart
  packages/firebase_ml_vision/example/lib/main.dart
  packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart
  packages/firebase_ml_vision/example/lib/picture_scanner.dart
  packages/firebase_ml_vision/example/lib/scanner_utils.dart
  packages/firebase_ml_vision/example/pubspec.yaml
  packages/firebase_ml_vision/example/test_driver/firebase_ml_vision.dart
  packages/firebase_ml_vision/example/test_driver/firebase_ml_vision_test.dart
  packages/firebase_ml_vision/example/test_driver/text_recognizer.dart
  packages/firebase_ml_vision/lib/src/barcode_detector.dart
  packages/firebase_ml_vision/lib/src/document_text_recognizer.dart
  packages/firebase_ml_vision/lib/src/face_detector.dart
  packages/firebase_ml_vision/lib/src/firebase_vision.dart
  packages/firebase_ml_vision/lib/src/image_labeler.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/document_text_recognizer_test.dart
  packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
Labels: cla: yes

#5231 chore: enable missing lints on firebase_analytics
  packages/firebase_analytics/all_lint_rules.yaml
  packages/firebase_analytics/analysis_options.yaml
  packages/firebase_analytics/firebase_analytics/example/lib/main.dart
  packages/firebase_analytics/firebase_analytics/example/lib/tabs_page.dart
  packages/firebase_analytics/firebase_analytics/example/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart
  packages/firebase_analytics/firebase_analytics/lib/observer.dart
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/test/firebase_analytics_test.dart
  packages/firebase_analytics/firebase_analytics/test/observer_test.dart
  packages/firebase_analytics/firebase_analytics_platform_interface/lib/firebase_analytics_platform_interface.dart
  packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
  packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_web/test/firebase_analytics_web_test.dart
Labels: cla: yes

#5232 chore: enable lints for firebase_remote_config
  packages/firebase_remote_config/all_lint_rules.yaml
  packages/firebase_remote_config/analysis_options.yaml
  packages/firebase_remote_config/firebase_remote_config/lib/src/remote_config.dart
  packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/test/firebase_remote_config_test.dart
  packages/firebase_remote_config/firebase_remote_config/test/mock.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/firebase_remote_config_platform_interface.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/method_channel/method_channel_firebase_remote_config.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/method_channel/utils/exception.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/platform_interface/platform_interface_firebase_remote_config.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/remote_config_value.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/pubspec.yaml
Labels: cla: yes

#5240 Deprecate admob
  packages/firebase_admob/CHANGELOG.md
  packages/firebase_admob/README.md
  packages/firebase_admob/pubspec.yaml
Labels: cla: yes

#5233 chore: enable lints for firebase_database
  packages/firebase_database/all_lint_rules.yaml
  packages/firebase_database/analysis_options.yaml
  packages/firebase_database/example/analysis_options.yaml
  packages/firebase_database/example/lib/main.dart
  packages/firebase_database/example/pubspec.yaml
  packages/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/lib/src/database_reference.dart
  packages/firebase_database/lib/src/event.dart
  packages/firebase_database/lib/src/utils/push_id_generator.dart
  packages/firebase_database/lib/ui/firebase_animated_list.dart
  packages/firebase_database/lib/ui/firebase_list.dart
  packages/firebase_database/lib/ui/firebase_sorted_list.dart
  packages/firebase_database/lib/ui/utils/stream_subscriber_mixin.dart
  packages/firebase_database/pubspec.yaml
  packages/firebase_database/test/firebase_database_test.dart
  packages/firebase_database/test/firebase_list_test.dart
Labels: cla: yes

#5254 chore: enable lints for firebase_ml_custom
  packages/firebase_ml_custom/all_lint_rules.yaml
  packages/firebase_ml_custom/analysis_options.yaml
  packages/firebase_ml_custom/example/analysis_options.yaml
  packages/firebase_ml_custom/example/lib/main.dart
  packages/firebase_ml_custom/example/pubspec.yaml
  packages/firebase_ml_custom/example/test_driver/firebase_ml_custom_test.dart
  packages/firebase_ml_custom/example/test_driver/firebase_model_manager.dart
  packages/firebase_ml_custom/lib/src/model_management/firebase_model_download_conditions.dart
  packages/firebase_ml_custom/lib/src/model_management/firebase_model_manager.dart
  packages/firebase_ml_custom/pubspec.yaml
  packages/firebase_ml_custom/test/firebase_ml_custom_test.dart
Labels: cla: yes

#5256 chore: enable lints for firebase_dynamic_links
  packages/firebase_dynamic_links/all_lint_rules.yaml
  packages/firebase_dynamic_links/analysis_options.yaml
  packages/firebase_dynamic_links/example/analysis_options.yaml
  packages/firebase_dynamic_links/example/lib/main.dart
  packages/firebase_dynamic_links/example/pubspec.yaml
  packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_dynamic_links/test/firebase_dynamic_links_e2e.dart
Labels: cla: yes

#5255 chore: enable lints for in_app_messaging
  packages/firebase_in_app_messaging/all_lint_rules.yaml
  packages/firebase_in_app_messaging/analysis_options.yaml
  packages/firebase_in_app_messaging/example/analysis_options.yaml
  packages/firebase_in_app_messaging/example/lib/main.dart
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_in_app_messaging/lib/firebase_in_app_messaging.dart
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_in_app_messaging/test/firebase_in_app_messaging_test.dart
Labels: cla: yes

#5171 fix(auth, web): correct use of underlying useEmulator API, sync not async
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
Labels: cla: yes

#5276 fix: upgrade `firebase` in firebase_analytics_web
  packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
Labels: cla: yes

#5262 docs(firebase_auth): fixed example code to delete a user
  docs/auth/usage.mdx
Labels: cla: yes

#5242 fix(cloud_firestore_web): Fix wrong cast (FirebaseExtended#5050)
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Labels: cla: yes

#5292 docs: fix typo in crashlytics docs
  docs/crashlytics/overview.mdx
Labels: cla: yes

#5253 chore: enable lints in firebase_performance
  melos.yaml
  packages/firebase_performance/all_lint_rules.yaml
  packages/firebase_performance/analysis_options.yaml
  packages/firebase_performance/example/analysis_options.yaml
  packages/firebase_performance/example/lib/main.dart
  packages/firebase_performance/example/pubspec.yaml
  packages/firebase_performance/example/test_driver/firebase_performance_e2e.dart
  packages/firebase_performance/lib/src/firebase_performance.dart
  packages/firebase_performance/lib/src/http_metric.dart
  packages/firebase_performance/lib/src/performance_attributes.dart
  packages/firebase_performance/lib/src/trace.dart
  packages/firebase_performance/pubspec.yaml
  packages/firebase_performance/test/firebase_performance_test.dart
Labels: cla: yes

#5329 chore: merge all analysis_options.yaml into one
  all_lint_rules.yaml
  analysis_options.yaml
  packages/cloud_firestore/analysis_options.yaml
  packages/cloud_functions/all_lint_rules.yaml
  packages/cloud_functions/analysis_options.yaml
  packages/cloud_functions/cloud_functions/example/analysis_options.yaml
  packages/firebase_admob/all_lint_rules.yaml
  packages/firebase_admob/analysis_options.yaml
  packages/firebase_admob/example/analysis_options.yaml
  packages/firebase_analytics/all_lint_rules.yaml
  packages/firebase_analytics/analysis_options.yaml
  packages/firebase_auth/all_lint_rules.yaml
  packages/firebase_auth/analysis_options.yaml
  packages/firebase_auth/firebase_auth/example/analysis_options.yaml
  packages/firebase_core/all_lint_rules.yaml
  packages/firebase_core/analysis_options.yaml
  packages/firebase_core/firebase_core/example/analysis_options.yaml
  packages/firebase_core/firebase_core/lib/src/firebase.dart
  packages/firebase_core/firebase_core/lib/src/firebase_app.dart
  packages/firebase_core/firebase_core/test/firebase_core_test.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_app.dart
  packages/firebase_core/firebase_core_platform_interface/test/platform_interface_tests/platform_interface_firebase_core_test.dart
  packages/firebase_crashlytics/all_lint_rules.yaml
  packages/firebase_crashlytics/analysis_options.yaml
  packages/firebase_crashlytics/firebase_crashlytics/example/analysis_options.yaml
  packages/firebase_database/all_lint_rules.yaml
  packages/firebase_database/analysis_options.yaml
  packages/firebase_database/example/analysis_options.yaml
  packages/firebase_database/test/firebase_list_test.dart
  packages/firebase_dynamic_links/all_lint_rules.yaml
  packages/firebase_dynamic_links/analysis_options.yaml
  packages/firebase_dynamic_links/example/analysis_options.yaml
  packages/firebase_in_app_messaging/all_lint_rules.yaml
  packages/firebase_in_app_messaging/analysis_options.yaml
  packages/firebase_in_app_messaging/example/analysis_options.yaml
  packages/firebase_messaging/all_lint_rules.yaml
  packages/firebase_messaging/analysis_options.yaml
  packages/firebase_messaging/firebase_messaging/example/analysis_options.yaml
  packages/firebase_ml_custom/all_lint_rules.yaml
  packages/firebase_ml_custom/analysis_options.yaml
  packages/firebase_ml_custom/example/analysis_options.yaml
  packages/firebase_ml_vision/all_lint_rules.yaml
  packages/firebase_ml_vision/analysis_options.yaml
  packages/firebase_ml_vision/example/analysis_options.yaml
  packages/firebase_performance/all_lint_rules.yaml
  packages/firebase_performance/analysis_options.yaml
  packages/firebase_performance/example/analysis_options.yaml
Labels: cla: yes

#5407 chore(repository): fix issue template discussion categories' links
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla: yes

#5187 fix(crashlytics)!: `checkForUnsentReports` should error if `isCrashlyticsCollectionEnabled` is false
  packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e.dart
  packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/platform_interface_tests/platform_interface_crashlytics_test.dart
Labels: cla: yes

#5406 docs(admob): update docs to reference new external plugin
  README.md
  docs/admob/usage.mdx
  docs/sidebars.js
  docs/versions.js
  website/plugins.js
  website/src/pages/index.tsx
Labels: cla: yes

#5369 fix(cloud_functions,web): use `kIsWeb` to check platform is Web
  packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart
  packages/cloud_functions/cloud_functions/test/firebase_functions_test.dart
Labels: cla: yes

#5342 chore: Remove note on updating changelog and major version from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#5421 fix: Added `android:` to `usesCleartextTraffic` in docs
  docs/installation/android.mdx
Labels: cla: yes

#5335 fix: cannot store null values in firestore on the web
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_change_e2e.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Labels: cla: yes

#5296 docs: update null-safety.mdx
  docs/null-safety.mdx
Labels: cla: yes

#5336 fix(messaging,nnbd): regression in `RemoteMessage.fromMap()` causing silent failure
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/test/remote_message_test.dart
Labels: cla: yes

#4748 docs: removed semicolon on single line return statement
  docs/firestore/usage.mdx
Labels: cla: yes

#4713 fix: update firebase_messaging_web homepage
  packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
Labels: cla: yes

#4671 docs(firebase-auth,apple): uninstallation warning for logged in users
  docs/auth/usage.mdx
Labels: cla: yes

#5429 chore(release): publish packages
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
  packages/cloud_functions/cloud_functions/CHANGELOG.md
  packages/cloud_functions/cloud_functions/pubspec.yaml
  packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml
  packages/cloud_functions/cloud_functions_web/CHANGELOG.md
  packages/cloud_functions/cloud_functions_web/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
  packages/firebase_auth/firebase_auth_web/CHANGELOG.md
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
  packages/firebase_core/firebase_core/CHANGELOG.md
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_core/firebase_core_web/CHANGELOG.md
  packages/firebase_core/firebase_core_web/pubspec.yaml
  packages/firebase_database/pubspec.yaml
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/CHANGELOG.md
  packages/firebase_messaging/firebase_messaging/pubspec.yaml
  packages/firebase_messaging/firebase_messaging_platform_interface/CHANGELOG.md
  packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml
  packages/firebase_messaging/firebase_messaging_web/CHANGELOG.md
  packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
  packages/firebase_ml_custom/pubspec.yaml
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_performance/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config_platform_interface/pubspec.yaml
  packages/firebase_storage/firebase_storage/pubspec.yaml
  packages/firebase_storage/firebase_storage_platform_interface/pubspec.yaml
  packages/firebase_storage/firebase_storage_web/CHANGELOG.md
  packages/firebase_storage/firebase_storage_web/pubspec.yaml
Labels: cla: yes

#5447 docs: Refer to Authentication emulator in docs
  docs/auth/usage.mdx
Labels: cla: yes

#5450 fix: remove incorrect ARCHS in ios examples
  packages/cloud_firestore/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_admob/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_analytics/firebase_analytics/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_database/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_dynamic_links/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
  packages/firebase_performance/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_remote_config/firebase_remote_config/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_storage/firebase_storage/example/ios/Runner.xcodeproj/project.pbxproj
Labels: cla: yes

#4571 docs(firebase_auth): fixed a typo in Usage section!
  AUTHORS
  docs/auth/usage.mdx
Labels: cla: yes

#4541 docs(firebase_auth): Facebook Auth Example Code Fix
  docs/auth/social.mdx
Labels: cla: yes

#5455 fix(firebase_crashlytics): Add Flutter dependency to podspec
  packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec
Labels: cla: yes

#5452 feat(messaging): android.tag property on Notification
  packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
  packages/firebase_messaging/firebase_messaging/example/lib/main.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
Labels: cla: yes

#5463 refactor(core): Remove deprecated gradle property `android.enableR8=true`
  packages/firebase_core/firebase_core/android/gradle.properties
Labels: cla: yes

#5443 fix(*): operator `==` takes `Object` parameter
  packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/blob.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/field_path.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/geo_point.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/internal/pointer.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_field_value.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/timestamp.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_web.dart
  packages/firebase_core/firebase_core/lib/src/firebase.dart
  packages/firebase_core/firebase_core/lib/src/firebase_app.dart
  packages/firebase_core/firebase_core/test/firebase_core_test.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_app.dart
  packages/firebase_core/firebase_core_platform_interface/test/platform_interface_tests/platform_interface_firebase_core_test.dart
  packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
  packages/firebase_storage/firebase_storage/lib/src/reference.dart
Labels: cla: yes

#5368 feat!: Migrate firebase_dynamic_links to sound null safety
  packages/firebase_dynamic_links/example/lib/main.dart
  packages/firebase_dynamic_links/example/pubspec.yaml
  packages/firebase_dynamic_links/lib/firebase_dynamic_links.dart
  packages/firebase_dynamic_links/lib/src/dynamic_link_parameters.dart
  packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_dynamic_links/test/firebase_dynamic_links_e2e.dart
  packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
Labels: cla: yes

#5341 feat!: Migrate firebase_analytics to sound null safety
  .github/workflows/firebase_analytics.yaml
  packages/firebase_analytics/firebase_analytics/analysis_options.yaml
  packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart
  packages/firebase_analytics/firebase_analytics/lib/observer.dart
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/test/firebase_analytics_test.dart
  packages/firebase_analytics/firebase_analytics/test/observer_test.dart
  packages/firebase_analytics/firebase_analytics_platform_interface/lib/firebase_analytics_platform_interface.dart
  packages/firebase_analytics/firebase_analytics_platform_interface/lib/method_channel_firebase_analytics.dart
  packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_platform_interface/test/firebase_analytics_platform_interface_test.dart
  packages/firebase_analytics/firebase_analytics_platform_interface/test/method_channel_firebase_analytics_test.dart
  packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
  packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_web/test/firebase_analytics_web_test.dart
Labels: cla: yes

#5430 fix: bump min Dart SDK constraint to 2.12.0
  melos.yaml
  packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
  packages/cloud_functions/cloud_functions/example/pubspec.yaml
  packages/cloud_functions/cloud_functions/pubspec.yaml
  packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml
  packages/cloud_functions/cloud_functions_web/pubspec.yaml
  packages/firebase_admob/example/pubspec.yaml
  packages/firebase_admob/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
  packages/firebase_core/firebase_core/example/pubspec.yaml
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
  packages/firebase_core/firebase_core_web/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/pubspec.yaml
  packages/firebase_database/example/pubspec.yaml
  packages/firebase_database/pubspec.yaml
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/pubspec.yaml
  packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml
  packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
  packages/firebase_ml_custom/example/pubspec.yaml
  packages/firebase_ml_custom/pubspec.yaml
  packages/firebase_ml_vision/example/pubspec.yaml
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_performance/example/pubspec.yaml
  packages/firebase_performance/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/example/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config_platform_interface/pubspec.yaml
  packages/firebase_storage/firebase_storage/example/pubspec.yaml
  packages/firebase_storage/firebase_storage/pubspec.yaml
  packages/firebase_storage/firebase_storage_platform_interface/pubspec.yaml
  packages/firebase_storage/firebase_storage_web/pubspec.yaml
Labels: cla: yes

#5469 chore(repository): Simplify CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#5465 docs: wording tweaks around plugin stability
  docs/installation/web.mdx
  docs/migration-guide.mdx
  docs/null-safety.mdx
  docs/overview.mdx
Labels: cla: yes

#5467 fix(android,remote_config): ensureInitialized() task should ignore return value (fixes #5222)
  packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
  packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/MethodCallHandlerImpl.java
  packages/firebase_remote_config/firebase_remote_config/example/test_driver/firebase_remote_config_e2e.dart
Labels: cla: yes

#5439 docs: stable channel is null-safe
  docs/analytics/overview.mdx
  docs/auth/overview.mdx
  docs/core/usage.mdx
  docs/crashlytics/overview.mdx
  docs/database/overview.mdx
  docs/firestore/overview.mdx
  docs/functions/overview.mdx
  docs/messaging/overview.mdx
  docs/performance/overview.mdx
  docs/remote-config/overview.mdx
  docs/storage/overview.mdx
  website/api.js
  website/plugins.js
Labels: cla: yes

#5477 docs(auth): reword print message in code snippet
  docs/firestore/usage.mdx
Labels: cla: yes

#5504 fix: [firebase_in_app_messaging] README code snippets
  packages/firebase_in_app_messaging/README.md
Labels: cla: yes

#5499 fix: Update README.md
  README.md
Labels: cla: yes

#5502 fix: Disable audio for camera controller in example app.
  packages/firebase_ml_vision/example/lib/camera_preview_scanner.dart
  packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart
Labels: cla: yes

#4251 fix(firebase_analytics): remove screen_view from reservedEventNames
  packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart
Labels: cla: yes

#3860 docs(firebase_crashlytics): update setup guide
  docs/_assets/crashlytics-init.png
  docs/_assets/enable-firebase-crashlytics.png
  docs/crashlytics/overview.mdx
  docs/crashlytics/usage.mdx
Labels: cla: yes

#5513 docs: Remove optional parameter from FirebaseAuth.instance.useEmulator
  docs/auth/usage.mdx
Labels: cla: yes

#5470 docs: discontinued admob
  website/plugins.js
  website/src/pages/index.tsx
Labels: cla: yes, plugin: admob, type: documentation

#5476 fix(firestore): made `QueryDocumentSnapshot.data()` non-nullable
  packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart
Labels: cla: yes, nnbd, plugin: cloud_firestore

#5518 fix(firebase_messaging): fix getNotificationSettings for null safety
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
Labels: cla: yes

#5520 docs: Upgrading to camera plugin 0.8.1
  packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart
  packages/firebase_ml_vision/example/pubspec.yaml
Labels: cla: yes

#5533 chore: Update cancel.yaml workflow to cancel all workflows.
  .github/workflows/cancel.yaml
  .github/workflows/firebase_admob.yaml
Labels: cla: yes
