Repository firebase/flutterfire, pull requests merged in 2021-04, with the labels that each got.

#1306 docs(database): add example for connecting to the default database
  packages/firebase_database/README.md
Labels: cla: yes

#5535 chore: Skip CI when editing only markdown files
  .github/workflows/all_plugins.yaml
  .github/workflows/firebase_admob.yaml
  .github/workflows/firebase_analytics.yaml
  .github/workflows/firebase_auth.yaml
  .github/workflows/firebase_core.yaml
  .github/workflows/firebase_crashlytics.yaml
  .github/workflows/firebase_database.yaml
  .github/workflows/firebase_firestore.yaml
  .github/workflows/firebase_functions.yaml
  .github/workflows/firebase_messaging.yaml
  .github/workflows/firebase_performance.yaml
  .github/workflows/firebase_remote_config.yaml
  .github/workflows/firebase_storage.yaml
Labels: cla: yes, type: enhancement

#4917 docs(auth): `PhoneAuthProvider.credential` returns an instance of `AuthCredential`
  docs/auth/phone.mdx
Labels: cla: yes

#5542 chore: add repository urls to pubspecs
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_functions/cloud_functions/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_core/firebase_core/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
  packages/firebase_database/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/pubspec.yaml
  packages/firebase_performance/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
  packages/firebase_storage/firebase_storage/pubspec.yaml
Labels: cla: yes

#5637 chore(workflows): add ability to cancel all but latest workflow run
  .github/workflows/cancel.yaml
Labels: cla: yes

#5653 fix(messaging): APN message with critical sound causing a hidden error
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
Labels: cla: yes

#5427 feat(crashlytics): fatal error crash report
  docs/crashlytics/usage.mdx
  packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart
  packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/platform_interface/platform_interface_crashlytics.dart
Labels: cla: yes, platform: android, platform: ios, plugin: crashlytics, type: enhancement

#5663 docs(cloud_functions): update emulator usage instructions
  docs/functions/usage.mdx
Labels: cla: yes

#5683 docs: Add github examples to the firebase docs
  docs/sidebars.js
Labels: cla: yes

#5485 fix(web, firestore): stop overwriting user errors
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
Labels: cla: yes, platform: web, plugin: cloud_firestore

#5682 fix: improve refFromURL http regex
  packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart
  packages/firebase_storage/firebase_storage/lib/src/utils.dart
  packages/firebase_storage/firebase_storage/test/firebase_storage_test.dart
  packages/firebase_storage/firebase_storage/test/utils_test.dart
Labels: cla: yes

#4394 fix(firebase_analytics): support complex data structures like list and map on Android
  packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
  packages/firebase_analytics/firebase_analytics/example/test_driver/firebase_analytics_e2e.dart
Labels: blocked: customer-response, cla: yes, platform: android, plugin: analytics

#5539 refactor(example,ml): android embedding v2
  packages/firebase_ml_vision/example/android/app/src/androidTest/java/io/flutter/plugins/firebasemlvision/EmbeddingV1ActivityTest.java
  packages/firebase_ml_vision/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_ml_vision/example/android/app/src/main/java/io/flutter/plugins/firebasemlvisionexample/EmbeddingV1Activity.java
  packages/firebase_ml_vision/example/android/app/src/main/java/io/flutter/plugins/firebasemlvisionexample/MainActivity.java
Labels: Needs Attention, cla: yes, platform: android

#1645 fix(ml_vision,ios): add additional null validations
  packages/firebase_ml_vision/example/assets/test_driver_license_barcode.png
  packages/firebase_ml_vision/example/test_driver/barcode_detector.dart
  packages/firebase_ml_vision/ios/Classes/BarcodeDetector.m
Labels: cla: yes, platform: ios, plugin: ml_vision, type: crash

#5698 docs(firestore): userChanges clarification
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
Labels: cla: yes

#5699 docs(crashlytics): update example
  docs/crashlytics/usage.mdx
Labels: cla: yes

#5723 chore(workflows): use new cancel-workflow-action release
  .github/workflows/cancel.yaml
Labels: cla: yes

#5675 feat: PhoneAuthProvider.credential and PhoneAuthProvider.credentialFromomToken now return a PhoneAuthCredential
  docs/auth/phone.mdx
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
  packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart
  packages/firebase_auth/firebase_auth/test/user_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/phone_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_user_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/platform_interface_tests/platform_interface_user_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/providers_tests/phone_auth_test.dart
Labels: cla: yes

#5740 chore: update drive dependency
  packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
  packages/cloud_functions/cloud_functions/example/pubspec.yaml
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
  packages/firebase_storage/firebase_storage/example/pubspec.yaml
Labels: cla: yes

#5540 feat!: Migrate firebase_performance to sound null safety
  packages/firebase_performance/lib/firebase_performance.dart
  packages/firebase_performance/lib/src/firebase_performance.dart
  packages/firebase_performance/lib/src/http_metric.dart
  packages/firebase_performance/lib/src/performance_attributes.dart
  packages/firebase_performance/lib/src/trace.dart
  packages/firebase_performance/test/firebase_performance_e2e.dart
  packages/firebase_performance/test/firebase_performance_test.dart
Labels: cla: yes, nnbd, plugin: performance

#5474 feat!: Migrate firebase_ml_vision to sound null safety
  packages/firebase_ml_vision/example/lib/camera_preview_scanner.dart
  packages/firebase_ml_vision/example/lib/colors.dart
  packages/firebase_ml_vision/example/lib/detector_painters.dart
  packages/firebase_ml_vision/example/lib/main.dart
  packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart
  packages/firebase_ml_vision/example/lib/picture_scanner.dart
  packages/firebase_ml_vision/example/lib/scanner_utils.dart
  packages/firebase_ml_vision/example/pubspec.yaml
  packages/firebase_ml_vision/example/test_driver/barcode_detector.dart
  packages/firebase_ml_vision/example/test_driver/document_text_recognizer.dart
  packages/firebase_ml_vision/example/test_driver/face_detector.dart
  packages/firebase_ml_vision/example/test_driver/firebase_ml_vision.dart
  packages/firebase_ml_vision/example/test_driver/firebase_ml_vision_test.dart
  packages/firebase_ml_vision/example/test_driver/image_labeler.dart
  packages/firebase_ml_vision/example/test_driver/text_recognizer.dart
  packages/firebase_ml_vision/lib/firebase_ml_vision.dart
  packages/firebase_ml_vision/lib/src/barcode_detector.dart
  packages/firebase_ml_vision/lib/src/document_text_recognizer.dart
  packages/firebase_ml_vision/lib/src/face_detector.dart
  packages/firebase_ml_vision/lib/src/firebase_vision.dart
  packages/firebase_ml_vision/lib/src/image_labeler.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_ml_vision/test/document_text_recognizer_test.dart
  packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
  packages/firebase_ml_vision/test/image_labeler_test.dart
Labels: Needs Attention, cla: yes, nnbd, plugin: ml_vision

#5676 feat: migrate in_app_messaging to sound null safety
  packages/firebase_in_app_messaging/example/lib/main.dart
  packages/firebase_in_app_messaging/example/pubspec.yaml
  packages/firebase_in_app_messaging/lib/firebase_in_app_messaging.dart
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_in_app_messaging/test/firebase_in_app_messaging_e2e.dart
  packages/firebase_in_app_messaging/test/firebase_in_app_messaging_test.dart
Labels: cla: yes

#5751 fix(cloud_firestore): conditionally pass options to docChanges
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
Labels: cla: yes

#5686 feat(firebase_remote_config)!: migrate to nullsafety
  packages/firebase_remote_config/firebase_remote_config/example/android/app/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfigexample/EmbeddingV1Activity.java
  packages/firebase_remote_config/firebase_remote_config/example/android/app/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfigexample/EmbeddingV1ActivityTest.java
  packages/firebase_remote_config/firebase_remote_config/example/lib/main.dart
  packages/firebase_remote_config/firebase_remote_config/example/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config/example/test_driver/firebase_remote_config_e2e.dart
  packages/firebase_remote_config/firebase_remote_config/example/test_driver/firebase_remote_config_e2e_test.dart
  packages/firebase_remote_config/firebase_remote_config/ios/Classes/FLTFirebaseRemoteConfigPlugin.m
  packages/firebase_remote_config/firebase_remote_config/lib/firebase_remote_config.dart
  packages/firebase_remote_config/firebase_remote_config/lib/src/remote_config.dart
  packages/firebase_remote_config/firebase_remote_config/test/firebase_remote_config_test.dart
  packages/firebase_remote_config/firebase_remote_config/test/mock.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/firebase_remote_config_platform_interface.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/method_channel/method_channel_firebase_remote_config.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/method_channel/utils/exception.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/platform_interface/platform_interface_firebase_remote_config.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/remote_config_settings.dart
  packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/remote_config_value.dart
Labels: cla: yes

#5441 refactor(firebase_database)!: Migrate to sound null-safety
  .github/workflows/firebase_database.yaml
  .github/workflows/scripts/build-example.sh
  .github/workflows/scripts/drive-example.sh
  packages/firebase_database/example/android/app/build.gradle
  packages/firebase_database/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/EmbeddingV1Activity.java
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/EmbeddingV1ActivityTest.java
  packages/firebase_database/example/android/app/src/main/java/io/flutter/plugins/firebasedatabaseexample/MainActivity.java
  packages/firebase_database/example/android/app/src/main/res/drawable/launch_background.xml
  packages/firebase_database/example/android/app/src/main/res/values/styles.xml
  packages/firebase_database/example/android/settings.gradle
  packages/firebase_database/example/lib/main.dart
  packages/firebase_database/example/pubspec.yaml
  packages/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/example/test_driver/firebase_database_e2e_test.dart
  packages/firebase_database/lib/firebase_database.dart
  packages/firebase_database/lib/src/database_reference.dart
  packages/firebase_database/lib/src/event.dart
  packages/firebase_database/lib/src/firebase_database.dart
  packages/firebase_database/lib/src/on_disconnect.dart
  packages/firebase_database/lib/src/query.dart
  packages/firebase_database/lib/src/utils/push_id_generator.dart
  packages/firebase_database/lib/ui/firebase_animated_list.dart
  packages/firebase_database/lib/ui/firebase_list.dart
  packages/firebase_database/lib/ui/firebase_sorted_list.dart
  packages/firebase_database/lib/ui/utils/stream_subscriber_mixin.dart
  packages/firebase_database/pubspec.yaml
  packages/firebase_database/test/firebase_database_test.dart
  packages/firebase_database/test/firebase_list_test.dart
  packages/firebase_database/test/test_common.dart
Labels: cla: yes, nnbd, plugin: database

#5766 fix(firebase_auth): ensure web is initialized before sending stream events
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
Labels: cla: yes

#5784 ci(web): switch back to ubuntu CI runners for testing with Firebase emulator suite
  .github/workflows/firebase_auth.yaml
  .github/workflows/firebase_firestore.yaml
  .github/workflows/firebase_functions.yaml
  packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart
Labels: cla: yes

#4464 chore: update Web plugins to use Firebase JS SDK version 8.4.1
  docs/versions.js
  packages/cloud_firestore/cloud_firestore/example/web/index.html
  packages/cloud_functions/cloud_functions/example/web/index.html
  packages/cloud_functions/cloud_functions_web/README.md
  packages/firebase_analytics/firebase_analytics/example/web/index.html
  packages/firebase_analytics/firebase_analytics_web/README.md
  packages/firebase_auth/firebase_auth/example/web/index.html
  packages/firebase_auth/firebase_auth_web/README.md
  packages/firebase_core/firebase_core/example/web/index.html
  packages/firebase_messaging/firebase_messaging/example/web/firebase-messaging-sw.js
  packages/firebase_messaging/firebase_messaging/example/web/index.html
  packages/firebase_storage/firebase_storage/example/web/index.html
Labels: cla: yes

#5783 refactor: Share guard functions accross plugins
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/internals.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
  packages/firebase_core/firebase_core/lib/src/internals.dart
  packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart
  packages/firebase_messaging/firebase_messaging_web/lib/src/internals.dart
  packages/firebase_messaging/firebase_messaging_web/lib/src/utils.dart
  packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/task_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/utils/errors.dart
Labels: cla: yes

#5709 fix(functions): return correct type on native
  .editorconfig
  .github/workflows/scripts/functions/src/index.ts
  packages/cloud_functions/cloud_functions/example/test_driver/cloud_functions_e2e.dart
  packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart
Labels: cla: yes

#5835 refactor: fix formatting
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_info.dart
  packages/firebase_ml_vision/lib/src/document_text_recognizer.dart
  packages/firebase_ml_vision/lib/src/image_labeler.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
Labels: cla: yes

#5834 fix(auth): uid can be null
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/user_info.dart
Labels: cla: yes

#4635 docs(firebase_auth): Add UserInfoCard widget in auth example SignInPage
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
Labels: cla: yes

#4407 fix(firebase_crashlytics): Include obfuscated stack traces
  packages/firebase_crashlytics/firebase_crashlytics/lib/firebase_crashlytics.dart
  packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
  packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart
  packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
Labels: cla: yes

#5563 fix(analytics, android): null values for events
  packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
Labels: cla: yes

#5718 fix(firebase_crashlytics): Avoid duplicate prints
  packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
Labels: cla: yes

#4221 fix(firebase_ml_vision): fixed image distortion in example
  packages/firebase_ml_vision/example/lib/picture_scanner.dart
Labels: cla: yes

#5765 fix(database): return ordered data
  packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java
  packages/firebase_database/example/android/app/build.gradle
  packages/firebase_database/example/android/app/google-services.json
  packages/firebase_database/example/ios/Runner/GoogleService-Info.plist
  packages/firebase_database/example/lib/main.dart
  packages/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/ios/Classes/FLTFirebaseDatabasePlugin.h
  packages/firebase_database/ios/Classes/FLTFirebaseDatabasePlugin.m
  packages/firebase_database/lib/src/database_reference.dart
  packages/firebase_database/lib/src/event.dart
  packages/firebase_database/lib/ui/firebase_list.dart
  packages/firebase_database/test/firebase_database_test.dart
Labels: cla: yes

#4287 docs(overview): update docs version of Firestore iOS SDK frameworks
  docs/overview.mdx
Labels: cla: yes

#5852 fix(cloud_firestore): Clear event listeners when firebase core is reinitialised
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
Labels: cla: yes

#4643 fix(firebase_auth): Move communication to EventChannels
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/AuthStateChannelStreamHandler.java
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/Constants.java
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/IdTokenChannelStreamHandler.java
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/PhoneNumberVerificationStreamHandler.java
  packages/firebase_auth/firebase_auth/example/test_driver/test_utils.dart
  packages/firebase_auth/firebase_auth/ios/Classes/FLTAuthStateChannelStreamHandler.m
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
  packages/firebase_auth/firebase_auth/ios/Classes/FLTIdTokenChannelStreamHandler.m
  packages/firebase_auth/firebase_auth/ios/Classes/FLTPhoneNumberVerificationStreamHandler.m
  packages/firebase_auth/firebase_auth/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h
  packages/firebase_auth/firebase_auth/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h
  packages/firebase_auth/firebase_auth/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h
  packages/firebase_auth/firebase_auth/ios/Classes/Public/FLTFirebaseAuthPlugin.h
  packages/firebase_auth/firebase_auth/macos/Classes/FLTAuthStateChannelStreamHandler.m
  packages/firebase_auth/firebase_auth/macos/Classes/FLTIdTokenChannelStreamHandler.m
  packages/firebase_auth/firebase_auth/macos/Classes/FLTPhoneNumberVerificationStreamHandler.m
  packages/firebase_auth/firebase_auth/macos/Classes/Private/FLTAuthStateChannelStreamHandler.h
  packages/firebase_auth/firebase_auth/macos/Classes/Private/FLTIdTokenChannelStreamHandler.h
  packages/firebase_auth/firebase_auth/macos/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_user_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/mock.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/platform_interface_tests/platform_interface_auth_test.dart
Labels: cla: yes

#5853 docs(firestore): handle non-existent document
  docs/firestore/usage.mdx
Labels: cla: yes

#2717 fix(database): refactor "removeObserver" to fix memory leak
  packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
  packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java
Labels: cla: yes

#5656 feat(firebase_auth): OAuthProvider.parameters is now non-nullable
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/oauth.dart
  packages/firebase_auth/firebase_auth_platform_interface/test/providers_tests/oauth_test.dart
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
  packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
Labels: cla: yes

#5847 fix: Incorrect type Annotation for GoogleAuthProvider.credential()
  docs/auth/social.mdx
Labels: cla: yes

#5862 docs: remove implicit-cast in the doc of AuthProviders
  docs/auth/error-handling.mdx
  docs/auth/social.mdx
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
  packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/facebook_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/github_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/google_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/twitter_auth.dart
Labels: cla: yes

#5863 fix(storage,web): secondary storage buckets now work as expected on Web
  packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart
  packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/firebase_interop.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
Labels: cla: yes

#3127 docs(firebase_dynamic_links): Open Android App directly without opening link in Browser.
  packages/firebase_dynamic_links/README.md
Labels: cla: yes

#5688 test(messaging): add additional messaging test coverage
  packages/firebase_messaging/firebase_messaging_platform_interface/test/notification_test.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/test/remote_message_test.dart
  packages/firebase_messaging/firebase_messaging_web/test/firebase_messaging_web_test.dart
Labels: cla: yes

#5867 fix: provide explicit types for StreamController(s).
  packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
Labels: cla: yes

#5869 fix(cloud_functions): bubble exceptions
  packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart
  packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/utils/exception.dart
  packages/cloud_functions/cloud_functions_platform_interface/test/method_channel/utils/exception_test.dart
  packages/cloud_functions/cloud_functions_web/lib/https_callable_web.dart
  packages/cloud_functions/cloud_functions_web/lib/utils.dart
Labels: cla: yes

#4354 fix(dynamic_links,ios): retry handling iOS universal link on network failure
  packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m
Labels: cla: yes

#5896 feat: update iOS Firebase SDK from 7.3 to 7.11
  docs/overview.mdx
  packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Labels: cla: yes

#5890 fix(firebase_auth,ios): Import all necessary headers from the header file.
  packages/firebase_auth/firebase_auth/ios/Classes/Public/FLTFirebaseAuthPlugin.h
Labels: cla: yes

#5940 fix(auth,web): fixed an issue where Web could not connect to the Firebase Auth emulator
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
Labels: cla: yes

#5945 feat(android,*): upgrade Firebase Android SDK to 26.8.0
  packages/firebase_core/firebase_core/android/gradle.properties
Labels: cla: yes

#5938 feat: Add withConverter function to CollectionReference, DocumentReference and Query
  docs/firestore/usage.mdx
  packages/cloud_firestore/cloud_firestore/example/analysis_options.yaml
  packages/cloud_firestore/cloud_firestore/example/lib/main.dart
  packages/cloud_firestore/cloud_firestore/example/lib/movie.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/collection_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/transaction.dart
  packages/cloud_firestore/cloud_firestore/lib/src/write_batch.dart
  packages/cloud_firestore/cloud_firestore/test/collection_reference_test.dart
  packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
Labels: cla: yes

#5987 fix(firebase_auth): Fix firebase_auth not being registered as a plugin
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes
