Repository firebase/flutterfire, pull requests merged in 2021-05, with the labels that each got.

#6008 fix(android,functions): possible null pointer exception when comparing error codes
  packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
Labels: cla: yes

#5944 fix(firebase_auth): authentication forceResendingToken int can be null on iOS
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
Labels: cla: yes

#5997 feat!: convert FieldPath parameters from dynamic to Object
  packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/test/document_snapshot_test.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_snapshot.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/set_options.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/set_options_test.dart
Labels: cla: yes

#5993 chore: update issue template to suggest providing example project
  .github/ISSUE_TEMPLATE/---bug-report.md
Labels: cla: yes

#5898 docs: use Flutter specific iOS plist file location
  docs/installation/ios.mdx
Labels: Needs Attention, cla: yes

#6015 feat(cloud_firestore)!: Add withConverter function to CollectionReference, DocumentReference and Query
  docs/firestore/usage.mdx
  packages/cloud_firestore/cloud_firestore/example/analysis_options.yaml
  packages/cloud_firestore/cloud_firestore/example/lib/main.dart
  packages/cloud_firestore/cloud_firestore/example/lib/movie.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/collection_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_change_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/field_value_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/geo_point_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/instance_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/timestamp_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/transaction_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/write_batch_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_change.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query_snapshot.dart
  packages/cloud_firestore/cloud_firestore/lib/src/transaction.dart
  packages/cloud_firestore/cloud_firestore/lib/src/utils/codec_utility.dart
  packages/cloud_firestore/cloud_firestore/lib/src/write_batch.dart
  packages/cloud_firestore/cloud_firestore/test/collection_reference_test.dart
  packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
Labels: cla: yes

#6021 docs: Add migration guide for cloud_firestore 2.0.0
  docs/firestore/2.0.0_migration.mdx
  docs/sidebars.js
Labels: cla: yes

#6020 docs: update contributing docs for publishing
  CONTRIBUTING.md
Labels: cla: yes

#6022 chore(release): publish packages
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
  packages/cloud_functions/cloud_functions/CHANGELOG.md
  packages/cloud_functions/cloud_functions/pubspec.yaml
  packages/firebase_analytics/firebase_analytics/CHANGELOG.md
  packages/firebase_analytics/firebase_analytics/pubspec.yaml
  packages/firebase_auth/firebase_auth/CHANGELOG.md
  packages/firebase_auth/firebase_auth/pubspec.yaml
  packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md
  packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
  packages/firebase_auth/firebase_auth_web/CHANGELOG.md
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
Labels: cla: yes

#6048 docs(cloud_firestore): update Source.cache doc
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/source.dart
Labels: cla: yes

#6051 docs(firebase_auth): Update the documentation of sendPasswordResetEmail
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
Labels: cla: yes

#6052 docs: update the "initializing flutterfire" snippet
  docs/overview.mdx
Labels: cla: yes

#6053 docs: improve the documentation about using runZoneGuarded for crashlytics
  docs/crashlytics/usage.mdx
Labels: cla: yes

#6054 docs: Add missing homepage/repository links
  packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
  packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
  packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml
  packages/cloud_functions/cloud_functions_web/pubspec.yaml
  packages/firebase_admob/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml
  packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
  packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
  packages/firebase_auth/firebase_auth_web/pubspec.yaml
  packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
  packages/firebase_core/firebase_core_web/pubspec.yaml
  packages/firebase_crashlytics/firebase_crashlytics_platform_interface/pubspec.yaml
  packages/firebase_dynamic_links/pubspec.yaml
  packages/firebase_in_app_messaging/pubspec.yaml
  packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml
  packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
  packages/firebase_ml_custom/pubspec.yaml
  packages/firebase_ml_vision/pubspec.yaml
  packages/firebase_remote_config/firebase_remote_config_platform_interface/pubspec.yaml
  packages/firebase_storage/firebase_storage_platform_interface/pubspec.yaml
  packages/firebase_storage/firebase_storage_web/pubspec.yaml
Labels: cla: yes

#6055 docs: fix readme incorrectly saying analytics supports macos
  README.md
Labels: cla: yes

#3263 fix(firebase_core, cloud_firestore): Fix FirebaseOptions hashCode
  packages/cloud_firestore/cloud_firestore/test/cloud_firestore_test.dart
  packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart
  packages/firebase_core/firebase_core_platform_interface/lib/firebase_core_platform_interface.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart
  packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
  packages/firebase_core/firebase_core_platform_interface/test/firebase_options_test.dart
Labels: cla: yes

#6100 docs(ml_vision): add discontinuation message and list alternatives
  packages/firebase_ml_vision/README.md
Labels: cla: yes

#6101 fix(firebase_auth): correctly cleanup Dictionary handlers
  packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Labels: cla: yes

#6092 docs: add QueryDocumentSnapshot to the list of classes that received a breaking change
  packages/cloud_firestore/cloud_firestore/CHANGELOG.md
Labels: cla: yes

#5915 docs: Start to listen once.
  docs/firestore/usage.mdx
Labels: cla: yes

#6111 docs: migrate firebase_analytics/example to null safety
  packages/firebase_analytics/firebase_analytics/example/lib/main.dart
  packages/firebase_analytics/firebase_analytics/example/lib/tabs_page.dart
Labels: cla: yes

#6109 feat(messaging): implement isSupported for web
  packages/firebase_messaging/firebase_messaging/example/test_driver/instance_e2e.dart
  packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
  packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/platform_interface/platform_interface_messaging.dart
  packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart
Labels: cla: yes

#6132 fix(cloud_firestore): pass GetOptions to web Query.get
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
Labels: cla: yes

#6133 chore: Enable more lints
  all_lint_rules.yaml
  analysis_options.yaml
  packages/firebase_core/analysis_options.yaml
  packages/firebase_core/firebase_core/lib/src/internals.dart
  packages/firebase_core/firebase_core/lib/src/interop_shimmer.dart
  packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_plugin.dart
  packages/firebase_core/firebase_core_platform_interface/test/method_channel_tests/method_channel_firebase_core_test.dart
  packages/firebase_core/firebase_core_web/lib/src/interop/utils/js_interop.dart
  packages/firebase_core/firebase_core_web/test/firebase_core_web_test.dart
  packages/firebase_database/firebase_database/test/firebase_database_test.dart
  packages/firebase_ml_vision/example/lib/detector_painters.dart
  packages/firebase_ml_vision/example/lib/picture_scanner.dart
  packages/firebase_storage/firebase_storage/example/lib/main.dart
  packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart
  packages/firebase_storage/firebase_storage_platform_interface/test/method_channel_tests/method_channel_firebase_storage_test.dart
  packages/firebase_storage/firebase_storage_platform_interface/test/method_channel_tests/method_channel_list_result_test.dart
  packages/firebase_storage/firebase_storage_platform_interface/test/mock.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart
  packages/firebase_storage/firebase_storage_web/test/metadata_cache_test.dart
Labels: cla: yes

#6160 docs: fix incorrect snippet
  docs/firestore/usage.mdx
Labels: cla: yes

#6171 docs(functions): region config example
  docs/functions/usage.mdx
Labels: cla: yes

#6037 feat(firestore): loadBundle() & namedQueryGet() implementation
  .github/workflows/scripts/firestore.rules
  docs/firestore/usage.mdx
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/LoadBundleStreamHandler.java
  packages/cloud_firestore/cloud_firestore/example/macos/Podfile
  packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
  packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart
  packages/cloud_firestore/cloud_firestore/example/test_driver/load_bundle_e2e.dart
  packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
  packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreWriter.m
  packages/cloud_firestore/cloud_firestore/ios/Classes/FLTLoadBundleStreamHandler.m
  packages/cloud_firestore/cloud_firestore/ios/Classes/Private/FLTLoadBundleStreamHandler.h
  packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/load_bundle_task.dart
  packages/cloud_firestore/cloud_firestore/lib/src/load_bundle_task_snapshot.dart
  packages/cloud_firestore/cloud_firestore/macos/Classes/FLTLoadBundleStreamHandler.m
  packages/cloud_firestore/cloud_firestore/macos/Classes/Private/FLTLoadBundleStreamHandler.h
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/cloud_firestore_platform_interface.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/load_bundle_task_state.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_load_bundle_task.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_load_bundle_task.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_load_bundle_task_snapshot.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/utils/load_bundle_task_state.dart
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/load_bundle_task_web.dart
Labels: cla: yes

#5936 feat(firebase_storage): add support for the Firebase Storage emulator via `useEmulator`
  .github/workflows/firebase_storage.yaml
  .github/workflows/scripts/firebase.json
  .github/workflows/scripts/start-firebase-emulator.sh
  .github/workflows/scripts/storage.rules
  docs/storage/usage.mdx
  packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStoragePlugin.java
  packages/firebase_storage/firebase_storage/example/android/app/src/main/AndroidManifest.xml
  packages/firebase_storage/firebase_storage/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_storage/firebase_storage/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  packages/firebase_storage/firebase_storage/example/ios/Runner/Info.plist
  packages/firebase_storage/firebase_storage/example/macos/Runner/Info.plist
  packages/firebase_storage/firebase_storage/example/test_driver/firebase_storage_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/list_result_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/reference_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart
  packages/firebase_storage/firebase_storage/example/test_driver/test_utils.dart
  packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
  packages/firebase_storage/firebase_storage/lib/firebase_storage.dart
  packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
  packages/firebase_storage/firebase_storage/test/firebase_storage_test.dart
  packages/firebase_storage/firebase_storage/test/mock.dart
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_firebase_storage.dart
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_reference.dart
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_task.dart
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/platform_interface/platform_interface_firebase_storage.dart
  packages/firebase_storage/firebase_storage_platform_interface/test/method_channel_tests/method_channel_firebase_storage_test.dart
  packages/firebase_storage/firebase_storage_platform_interface/test/method_channel_tests/method_channel_reference_test.dart
  packages/firebase_storage/firebase_storage_platform_interface/test/platform_interface_tests/platform_interface_firebase_storage_test.dart
  packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
  packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart
  packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart
  packages/firebase_storage/firebase_storage_web/lib/src/utils/metadata.dart
Labels: blocked: firebase-sdk, cla: yes, plugin: storage

#6188 chore: fix format errors
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_info.dart
  packages/firebase_ml_vision/lib/src/document_text_recognizer.dart
  packages/firebase_ml_vision/lib/src/image_labeler.dart
  packages/firebase_ml_vision/lib/src/text_recognizer.dart
Labels: cla: yes

#6193 docs(app_check): Add missing `.instance`
  docs/app-check/usage.mdx
Labels: cla: yes

#6190 docs: Add Flutter Favorite badge
  packages/cloud_firestore/cloud_firestore/README.md
  packages/cloud_functions/cloud_functions/README.md
  packages/firebase_auth/firebase_auth/README.md
  packages/firebase_core/firebase_core/README.md
  packages/firebase_crashlytics/firebase_crashlytics/README.md
  packages/firebase_messaging/firebase_messaging/README.md
  packages/firebase_storage/firebase_storage/README.md
  resources/flutter_favorite.png
Labels: cla: yes

#6187 fix(firebase_database): Fix a null exception when using `runTransaction` with Maps.
  packages/firebase_database/firebase_database/example/pubspec.yaml
  packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/firebase_database/lib/src/database_reference.dart
  packages/firebase_database/firebase_database/lib/src/event.dart
Labels: cla: yes

#6228 docs(ml_custom): reinstate ml_custom as beta
  website/plugins.js
Labels: cla: yes

#6229 docs: document melos graduate packages
  CONTRIBUTING.md
Labels: cla: yes

#6241 docs(auth): codeSent doc update
  docs/auth/phone.mdx
Labels: cla: yes

#6221 fix(firebase_firestore): Update Cloud Firestore Usage.mx
  docs/firestore/usage.mdx
Labels: cla: yes

#6218 fix(firebase_firestore): fix typo on firebase_firestore real time example
  docs/firestore/usage.mdx
Labels: cla: yes

#6245 docs(firebase-auth): remove suggestion to handle `user-not-found` when using sendSignInLinkToEmail()
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
Labels: cla: yes

#6225 test(firestore): update and assert documentId field & isNotEqualTo filter test
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/test/query_test.dart
Labels: cla: yes
