Repository firebase/flutterfire, pull requests merged in 2021-09, with the labels that each got.

#6942 fix: Update firestore documentation usage.mdx
  docs/firestore/usage.mdx
Labels: cla: yes

#6917 fix(firebase_analytics): Fix incorrect type name in error message
  packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
Labels: cla: yes

#6946 fix(auth, android): use Locale.ROOT while processing error code
  packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPluginException.java
Labels: cla: yes

#6931 test(auth): Fix pre-existing HintCode.UNNECESSARY_TYPE_CHECK_TRUE
  packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart
Labels: cla: yes

#6943 chore(crashlytics): update example
  packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart
Labels: cla: yes

#6920 feat(firebase_performance): add web support to the plugin
  .vscode/settings.json
  packages/firebase_performance/firebase_performance/README.md
  packages/firebase_performance/firebase_performance/example/.firebaserc
  packages/firebase_performance/firebase_performance/example/.gitignore
  packages/firebase_performance/firebase_performance/example/README.md
  packages/firebase_performance/firebase_performance/example/firebase.json
  packages/firebase_performance/firebase_performance/example/lib/main.dart
  packages/firebase_performance/firebase_performance/example/pubspec.yaml
  packages/firebase_performance/firebase_performance/example/test_driver/firebase_performance_e2e.dart
  packages/firebase_performance/firebase_performance/example/web/favicon.png
  packages/firebase_performance/firebase_performance/example/web/first-input-delay.js
  packages/firebase_performance/firebase_performance/example/web/icons/Icon-192.png
  packages/firebase_performance/firebase_performance/example/web/icons/Icon-512.png
  packages/firebase_performance/firebase_performance/example/web/index.html
  packages/firebase_performance/firebase_performance/example/web/manifest.json
  packages/firebase_performance/firebase_performance/pubspec.yaml
  packages/firebase_performance/firebase_performance_web/.gitignore
  packages/firebase_performance/firebase_performance_web/.metadata
  packages/firebase_performance/firebase_performance_web/CHANGELOG.md
  packages/firebase_performance/firebase_performance_web/LICENSE
  packages/firebase_performance/firebase_performance_web/README.md
  packages/firebase_performance/firebase_performance_web/lib/firebase_performance_web.dart
  packages/firebase_performance/firebase_performance_web/lib/src/http_metric.dart
  packages/firebase_performance/firebase_performance_web/lib/src/trace.dart
  packages/firebase_performance/firebase_performance_web/pubspec.yaml
  packages/firebase_performance/firebase_performance_web/test/firebase_performance_web_test.dart
Labels: cla: yes

#6928 refactor: Reduce hash conflicts on objects
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/lib/src/snapshot_cache.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart
  packages/cloud_firestore/cloud_firestore_platform_interface/test/settings_test.dart
  packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
Labels: cla: yes

#6961 fix(messaging): was creating a new instance each time
  packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
Labels: cla: yes

#6930 fix(firestore, web): implement missing getter for settings on Firestore web
  packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
Labels: cla: yes

#6977 chore: fix analyze issues
  .github/workflows/all_plugins.yaml
  packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
  packages/firebase_database/firebase_database/example/macos/.gitignore
  packages/firebase_performance/firebase_performance/example/pubspec.yaml
  packages/firebase_performance/firebase_performance_web/lib/firebase_performance_web.dart
  packages/firebase_performance/firebase_performance_web/test/firebase_performance_web_test.dart
  packages/firebase_remote_config/firebase_remote_config/example/macos/.gitignore
  packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_firebase_storage.dart
Labels: cla: yes

#6974 revert: Firestore cache snapshot connections with underlying native listener (#6819)
  packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
  packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/lib/src/snapshot_cache.dart
  packages/cloud_firestore/cloud_firestore/pubspec.yaml
  packages/cloud_firestore/cloud_firestore/test/snapshot_cache_test.dart
Labels: cla: yes

#6980 docs(auth): bump plugins versions to null-safe
  docs/auth/social.mdx
Labels: cla: yes

#6965 chore(crashlytics): fix example to include "ensureInitialized" within runZonedGuarded
  packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart
Labels: cla: yes

#6982 fix(firebase_functions): android V2 embedding
  packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
Labels: cla: yes, plugin: functions

#6986 docs(performance): remove usage of private link address
  packages/firebase_performance/firebase_performance/README.md
Labels: cla: yes

#6990 chore(firebase_messaging): migrate example app to null-safety
  packages/firebase_messaging/firebase_messaging/example/lib/main.dart
  packages/firebase_messaging/firebase_messaging/example/lib/message.dart
  packages/firebase_messaging/firebase_messaging/example/lib/message_list.dart
  packages/firebase_messaging/firebase_messaging/example/lib/permissions.dart
  packages/firebase_messaging/firebase_messaging/example/lib/token_monitor.dart
  packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
  packages/firebase_messaging/firebase_messaging/example/test_driver/firebase_messaging_e2e.dart
  packages/firebase_messaging/firebase_messaging/example/test_driver/firebase_messaging_e2e_test.dart
  packages/firebase_messaging/firebase_messaging/example/test_driver/test_utils.dart
Labels: cla: yes

#6995 docs(firebase_auth): fix twitter sign in docs
  docs/auth/social.mdx
Labels: cla: yes

#6997 fix(firestore): an issue where `Query.==` throws when using `withConverter`
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
  packages/cloud_firestore/cloud_firestore/test/query_test.dart
Labels: cla: yes

#6952 feat(firebase_database)!: add web support to the plugin
  .github/workflows/firebase_database.yaml
  packages/firebase_database/firebase_database/README.md
  packages/firebase_database/firebase_database/example/lib/main.dart
  packages/firebase_database/firebase_database/example/pubspec.yaml
  packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/firebase_database/example/test_driver/query_e2e.dart
  packages/firebase_database/firebase_database/example/web/index.html
  packages/firebase_database/firebase_database/lib/src/firebase_database.dart
  packages/firebase_database/firebase_database/lib/ui/firebase_sorted_list.dart
  packages/firebase_database/firebase_database/pubspec.yaml
  packages/firebase_database/firebase_database_platform_interface/lib/firebase_database_platform_interface.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_database.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_database_reference.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/database_reference.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/event.dart
  packages/firebase_database/firebase_database_platform_interface/test/firebase_database_test.dart
  packages/firebase_database/firebase_database_web/.gitignore
  packages/firebase_database/firebase_database_web/.metadata
  packages/firebase_database/firebase_database_web/CHANGELOG.md
  packages/firebase_database/firebase_database_web/LICENSE
  packages/firebase_database/firebase_database_web/README.md
  packages/firebase_database/firebase_database_web/analysis_options.yaml
  packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart
  packages/firebase_database/firebase_database_web/lib/src/database_reference_web.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/app.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/app_interop.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/data_snapshot_interop.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/database_interop.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/firebase_interop.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/query_interop.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/reference_interop.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/utils/utils.dart
  packages/firebase_database/firebase_database_web/lib/src/ondisconnect_web.dart
  packages/firebase_database/firebase_database_web/lib/src/query_web.dart
  packages/firebase_database/firebase_database_web/lib/src/utils/snapshot_utils.dart
  packages/firebase_database/firebase_database_web/pubspec.yaml
Labels: cla: yes

#7008 docs(performance): add web support announcement and instructions.
  README.md
  docs/performance/overview.mdx
  website/plugins.js
Labels: cla: yes

#7045 refactor(database): rename reference() to ref([String? path])
  packages/firebase_database/firebase_database/README.md
  packages/firebase_database/firebase_database/example/ios/Runner/GoogleService-Info.plist
  packages/firebase_database/firebase_database/example/lib/main.dart
  packages/firebase_database/firebase_database/example/macos/Runner.xcodeproj/project.pbxproj
  packages/firebase_database/firebase_database/example/macos/Runner/GoogleService-Info.plist
  packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/firebase_database/example/test_driver/query_e2e.dart
  packages/firebase_database/firebase_database/lib/src/database_reference.dart
  packages/firebase_database/firebase_database/lib/src/firebase_database.dart
  packages/firebase_database/firebase_database/lib/src/on_disconnect.dart
  packages/firebase_database/firebase_database/lib/src/query.dart
  packages/firebase_database/firebase_database_platform_interface/lib/firebase_database_platform_interface.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_database.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_database_reference.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_on_disconnect.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_query.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/database_reference.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/on_disconnect.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/query.dart
  packages/firebase_database/firebase_database_platform_interface/test/firebase_database_test.dart
  packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart
  packages/firebase_database/firebase_database_web/lib/src/database_reference_web.dart
  packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
  packages/firebase_database/firebase_database_web/lib/src/ondisconnect_web.dart
  packages/firebase_database/firebase_database_web/lib/src/query_web.dart
Labels: cla: yes

#7003 fix(firebase_storage): fix localhost url parsing for Storage Emulator
  packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart
  packages/firebase_storage/firebase_storage/lib/src/utils.dart
Labels: cla: yes

#7047 chore: remove google-signin plugin temporarily to fix CI
  packages/firebase_auth/firebase_auth/example/android/build.gradle
  packages/firebase_auth/firebase_auth/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_auth/firebase_auth/example/ios/Flutter/AppFrameworkInfo.plist
  packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
  packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
  packages/firebase_auth/firebase_auth/example/pubspec.yaml
Labels: cla: yes

#7001 fix(firebase_database): List of values erroring on transaction result
  packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart
  packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/event.dart
Labels: cla: yes

#7053 chore: update gradle for analytics example app
  packages/firebase_analytics/firebase_analytics/example/android/build.gradle
  packages/firebase_analytics/firebase_analytics/example/android/gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#7054 chore: update gradle version across packages
  packages/cloud_firestore/cloud_firestore/example/android/build.gradle
  packages/cloud_firestore/cloud_firestore/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/cloud_functions/cloud_functions/example/android/build.gradle
  packages/cloud_functions/cloud_functions/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_app_check/firebase_app_check/example/android/build.gradle
  packages/firebase_core/firebase_core/example/android/build.gradle
  packages/firebase_core/firebase_core/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_crashlytics/firebase_crashlytics/example/android/build.gradle
  packages/firebase_crashlytics/firebase_crashlytics/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_database/firebase_database/example/android/build.gradle
  packages/firebase_database/firebase_database/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_dynamic_links/example/android/app/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_dynamic_links/example/android/build.gradle
  packages/firebase_dynamic_links/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_in_app_messaging/example/android/build.gradle
  packages/firebase_in_app_messaging/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_messaging/firebase_messaging/example/android/build.gradle
  packages/firebase_messaging/firebase_messaging/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_ml_custom/example/android/build.gradle
  packages/firebase_ml_custom/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_performance/firebase_performance/example/android/build.gradle
  packages/firebase_performance/firebase_performance/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_remote_config/firebase_remote_config/example/android/build.gradle
  packages/firebase_remote_config/firebase_remote_config/example/android/gradle/wrapper/gradle-wrapper.properties
  packages/firebase_storage/firebase_storage/example/android/build.gradle
  packages/firebase_storage/firebase_storage/example/android/gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#7075 fix: fixed a bug where `withConverter.endBeforeDocument` incorrectly behaved as `endAtDocument`
  packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
  packages/cloud_firestore/cloud_firestore/lib/src/query.dart
Labels: cla: yes

#7079 docs(firebase_messaging): RemoteMessage? returned from getInitialMessage is nullable
  docs/messaging/notifications.mdx
Labels: cla: yes

#7083 feat: bump Firebase iOS SDK to `8.7.0` & Android SDK to `28.4.1`
  docs/overview.mdx
  packages/firebase_core/firebase_core/android/gradle.properties
  packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Labels: cla: yes

#7067 docs: remove `main.dart.js` script from `index.html` for web setup.
  docs/installation/web.mdx
Labels: cla: yes

#7058 docs: update melos example macos description
  melos.yaml
Labels: cla: yes

#7088 fix(firebase_messaging): Fix crash on Android in onDetachedFromEngine
  packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
Labels: cla: yes

#7015 docs: update apple-integration.mdx line numbers
  docs/messaging/apple-integration.mdx
Labels: cla: yes

#7087 fix(cloud_firestore): propagate query index link to firebase console for user
  packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreException.java
  packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreUtils.m
Labels: cla: yes

#7096 docs(firebase_messaging): update import to "firebase_messaging"
  docs/messaging/overview.mdx
Labels: cla: yes

#7037 docs(analytics): boolean parameters are not supported for GA custom definitions.
  packages/firebase_analytics/firebase_analytics/example/lib/main.dart
Labels: cla: yes

#7081 docs(firebase_dynamic_links): changed "ibn" to "ibi" iOS param name in long dynamic link example
  packages/firebase_dynamic_links/README.md
Labels: cla: yes

#7050 fix(firebase_auth): allow setLanguage to accept null
  packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
  packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
  packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
Labels: cla: yes, plugin: auth

#7020 fix: value encoding fails when using `DocumentReference` & `withConverter`
  packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
  packages/cloud_firestore/cloud_firestore/lib/src/utils/codec_utility.dart
  packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart
Labels: cla: yes
