Repository firebase/flutterfire, pull requests merged in 2022-01, with the labels that each got.

#7234 docs(firebase_messaging): Provide fallback for `messageId` field for web as JS SDK does not have.
  packages/firebase_messaging/firebase_messaging/example/lib/message.dart
Labels: cla: yes

#7466 docs(firebase_messaging): Fix pod install for ImageNotification due to missing use_frameworks! flag.
  docs/messaging/apple-integration.mdx
Labels: cla: yes

#7687 fix(firebase_messaging): Make Web `deleteToken()` API a Future so it resolves only when completed.
  packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging.dart
  packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging_interop.dart
Labels: ready-to-merge

#6897 fix(firebase_core): Fix `FirebaseException` error code bug by making default value: "unknown".
  packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart
Labels: cla: yes, ready-to-merge

#7683 fix(firebase_auth): Add support for`dynamicLinkDomain` property to `ActionCodeSetting` for web.
  packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
  packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
Labels: ready-to-merge

#7873 docs(firebase_app_installations): Update usage.mdx to use correct implementation of `FirebaseInstallations` class.
  docs/installations/usage.mdx
Labels: cla: yes

#7859 fix(firebase_database): Fix `MissingPluginException` caused by malformed EventChannel name.
  packages/firebase_database/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
  packages/firebase_database/firebase_database/ios/Classes/FLTFirebaseDatabasePlugin.m
Labels: plugin: database, platform: android, platform: ios
